export interface VisualOverviewItem {
  id: string;
  shape: string;
  family: string;
  meaning: string;
  colorClass: string;
  iconType: string;
}

export interface RoadSignItem {
  id: string;
  code?: string;
  name: string;
  description?: string;
  meaning: string;
  category: 'danger' | 'priority' | 'interdiction' | 'fin_interdiction' | 'obligation' | 'fin_obligation' | 'indication' | 'balise' | 'passage_niveau' | 'temporaire' | 'panonceau';
  categoryLabel: string;
  iconType: string;
  imageFallback?: string;
  ruleTag?: string;
  accentColor?: string;
}

export interface ReferenceImageDoc {
  id: string;
  title: string;
  subtitle: string;
  imageUrl: string;
  category: string;
  badge: string;
}

export const VISUAL_OVERVIEW: VisualOverviewItem[] = [
  {
    id: 'rep-danger',
    shape: 'Triangle à bord rouge',
    family: 'Danger',
    meaning: '« Attention : un risque arrive »',
    colorClass: 'bg-red-500 text-white',
    iconType: 'triangle-danger',
  },
  {
    id: 'rep-cedez',
    shape: 'Triangle inversé à bord rouge',
    family: 'Cédez le passage',
    meaning: '« Je laisse passer si nécessaire »',
    colorClass: 'bg-red-500 text-white',
    iconType: 'triangle-cedez',
  },
  {
    id: 'rep-stop',
    shape: 'Octogone rouge',
    family: 'STOP',
    meaning: '« Je m’arrête obligatoirement »',
    colorClass: 'bg-red-600 text-white',
    iconType: 'octogon-stop',
  },
  {
    id: 'rep-interdiction',
    shape: 'Rond blanc à bord rouge',
    family: 'Interdiction',
    meaning: '« Je ne dois pas faire / entrer »',
    colorClass: 'bg-red-500 text-white',
    iconType: 'circle-interdiction',
  },
  {
    id: 'rep-obligation',
    shape: 'Rond bleu',
    family: 'Obligation',
    meaning: '« Je dois suivre cette instruction »',
    colorClass: 'bg-blue-600 text-white',
    iconType: 'circle-obligation',
  },
  {
    id: 'rep-priorite',
    shape: 'Losange jaune',
    family: 'Priorité',
    meaning: '« Ma route est prioritaire »',
    colorClass: 'bg-amber-400 text-slate-900',
    iconType: 'diamond-priority',
  },
  {
    id: 'rep-indication',
    shape: 'Carré / rectangle bleu',
    family: 'Indication ou service',
    meaning: '« Information utile »',
    colorClass: 'bg-sky-600 text-white',
    iconType: 'square-indication',
  },
  {
    id: 'rep-temporaire',
    shape: 'Fond jaune',
    family: 'Temporaire',
    meaning: '« Travaux, déviation ou règle provisoire »',
    colorClass: 'bg-yellow-400 text-slate-900',
    iconType: 'yellow-temp',
  },
  {
    id: 'rep-panonceau',
    shape: 'Petit panneau sous le principal',
    family: 'Panonceau',
    meaning: '« Précision : distance, durée, usagers concernés… »',
    colorClass: 'bg-slate-700 text-white',
    iconType: 'small-panonceau',
  },
];

export const REFERENCE_DOCS: ReferenceImageDoc[] = [
  {
    id: 'doc-danger',
    title: 'Planche Officielle : Panneaux de Danger & Vigilance',
    subtitle: 'Signaux de danger routier avec illustrations et recommandations de conduite.',
    imageUrl: '/panneau/1.webp',
    category: 'Danger',
    badge: 'Manuel Officiel',
  },
  {
    id: 'doc-priorite-danger',
    title: 'Répertoire Visuel : Priorités, Dangers & Limitations',
    subtitle: 'Tableau synthétique regroupant plus de 200 panneaux et signaux de position.',
    imageUrl: '/panneau/1716186500.webp',
    category: 'Priorité & Danger',
    badge: 'Guide Synthétique',
  },
  {
    id: 'doc-directionnel',
    title: 'Panneaux Directionnels, Couleurs & Fonctions (Cameroun / CEMAC)',
    subtitle: 'Règles de lecture des itinéraires autoroutiers, nationaux, secondaires et déviations.',
    imageUrl: '/panneau/1753616572.webp',
    category: 'Directionnel & CEMAC',
    badge: 'Spécial Cameroun',
  },
];

export const ALL_ROAD_SIGNS: RoadSignItem[] = [
  // ================= 1. DANGER ET VIGILANCE =================
  {
    id: 'sign-a1a',
    code: 'A1a',
    name: 'Virage dangereux à gauche',
    meaning: 'Ralentir avant le virage, rester à droite et éviter tout dépassement dangereux.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-turn-left',
    ruleTag: 'Ralentir & serrer à droite',
  },
  {
    id: 'sign-a1b',
    code: 'A1b',
    name: 'Virage dangereux à droite',
    meaning: 'Même règle : réduire l’allure avant d’entrer dans le virage.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-turn-right',
    ruleTag: 'Ralentir avant virage',
  },
  {
    id: 'sign-a1c',
    code: 'A1c',
    name: 'Succession de virages, premier à droite',
    meaning: 'Prévoir plusieurs changements de direction ; ne pas accélérer entre les virages.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-double-turn-right',
    ruleTag: 'Zone sinueuse',
  },
  {
    id: 'sign-a1d',
    code: 'A1d',
    name: 'Succession de virages, premier à gauche',
    meaning: 'Adapter la vitesse à toute la zone sinueuse.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-double-turn-left',
    ruleTag: 'Zone sinueuse',
  },
  {
    id: 'sign-a2a',
    code: 'A2a',
    name: 'Cassis ou dos-d’âne',
    meaning: 'Ralentir pour éviter perte de contrôle, choc ou détérioration du véhicule.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-bump-double',
    ruleTag: 'Ralentir fortement',
  },
  {
    id: 'sign-a2b',
    code: 'A2b',
    name: 'Ralentisseur de type dos-d’âne',
    meaning: 'Passer très lentement ; attention aux motos, taxis et piétons.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-bump-single',
    ruleTag: 'Vitesse max 30 km/h',
  },
  {
    id: 'sign-a3',
    code: 'A3',
    name: 'Chaussée rétrécie',
    meaning: 'La route devient moins large : ralentir et se préparer à croiser difficilement.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-narrow-both',
    ruleTag: 'Croisement difficile',
  },
  {
    id: 'sign-a3a',
    code: 'A3a',
    name: 'Chaussée rétrécie par la droite',
    meaning: 'La voie se resserre du côté droit.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-narrow-right',
    ruleTag: 'Rétrécissement droite',
  },
  {
    id: 'sign-a3b',
    code: 'A3b',
    name: 'Chaussée rétrécie par la gauche',
    meaning: 'La voie se resserre du côté gauche.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-narrow-left',
    ruleTag: 'Rétrécissement gauche',
  },
  {
    id: 'sign-a4',
    code: 'A4',
    name: 'Chaussée particulièrement glissante',
    meaning: 'Éviter freinage brutal, accélération brutale et coup de volant.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-slippery',
    ruleTag: 'Conduite souple',
  },
  {
    id: 'sign-a6',
    code: 'A6',
    name: 'Pont mobile',
    meaning: 'Risque d’ouverture du pont ; respecter feux, barrières et consignes.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-movable-bridge',
    ruleTag: 'Arrêt possible',
  },
  {
    id: 'sign-a7',
    code: 'A7',
    name: 'Passage à niveau avec barrières ou demi-barrières',
    meaning: 'Ralentir ; s’arrêter si les feux clignotent ou si les barrières se ferment.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-level-crossing-guarded',
    ruleTag: 'Passage gardé',
  },
  {
    id: 'sign-a8',
    code: 'A8',
    name: 'Passage à niveau sans barrière',
    meaning: 'Danger ferroviaire sans protection physique : regarder et écouter avant de franchir.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-level-crossing-train',
    ruleTag: 'Vigilance extrême',
  },
  {
    id: 'sign-a13a',
    code: 'A13a',
    name: 'Endroit fréquenté par les enfants',
    meaning: 'Zone scolaire ou lieu fréquenté par les enfants ; rouler très lentement.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-children',
    ruleTag: 'Zone scolaire',
  },
  {
    id: 'sign-a13b',
    code: 'A13b',
    name: 'Passage pour piétons',
    meaning: 'Anticiper une traversée ; céder aux piétons déjà engagés.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-pedestrian-crossing',
    ruleTag: 'Priorité piéton',
  },
  {
    id: 'sign-a14',
    code: 'A14',
    name: 'Autres dangers',
    meaning: 'Danger non précisé ou précisé par un panonceau : ralentir et identifier la situation.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-general-exclamation',
    ruleTag: 'Attention générale',
  },
  {
    id: 'sign-a15a',
    code: 'A15a1 / A15a2',
    name: 'Passage d’animaux domestiques',
    meaning: 'Bétail, chèvres, moutons, bovins : ralentir, ne pas klaxonner agressivement.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-cattle',
    ruleTag: 'Bétail & troupeaux',
  },
  {
    id: 'sign-a15b',
    code: 'A15b',
    name: 'Passage d’animaux sauvages',
    meaning: 'Risque d’animaux imprévisibles ; réduire la vitesse, surtout la nuit.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-wild-animals',
    ruleTag: 'Faune sauvage',
  },
  {
    id: 'sign-a15c',
    code: 'A15c',
    name: 'Passage de cavaliers',
    meaning: 'Présence possible de chevaux et cavaliers ; dépasser largement et doucement.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-horse-rider',
    ruleTag: 'Cavaliers',
  },
  {
    id: 'sign-a16',
    code: 'A16',
    name: 'Descente dangereuse',
    meaning: 'Utiliser un rapport inférieur, garder le contrôle et éviter de rouler au point mort.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-steep-hill',
    ruleTag: 'Frein moteur',
  },
  {
    id: 'sign-a17',
    code: 'A17',
    name: 'Annonce de feux tricolores',
    meaning: 'Feux de signalisation à venir ; anticiper un feu rouge ou un ralentissement.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-traffic-light',
    ruleTag: 'Feux tricolores',
  },
  {
    id: 'sign-a18',
    code: 'A18',
    name: 'Circulation dans les deux sens',
    meaning: 'Fin d’une chaussée à sens unique ou arrivée sur une route à double sens.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-two-way',
    ruleTag: 'Double sens',
  },
  {
    id: 'sign-a19',
    code: 'A19',
    name: 'Chute de pierres',
    meaning: 'Risque de pierres sur la chaussée ou de chute depuis un talus.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-falling-rocks',
    ruleTag: 'Chute d’éboulis',
  },
  {
    id: 'sign-a20',
    code: 'A20',
    name: 'Débouché sur quai ou berge',
    meaning: 'Risque de chute dans l’eau ; ralentir fortement.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-quayside',
    ruleTag: 'Berge / eau',
  },
  {
    id: 'sign-a21',
    code: 'A21',
    name: 'Débouché de cyclistes',
    meaning: 'Des cyclistes peuvent arriver de droite ou de gauche.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-cyclists',
    ruleTag: 'Cyclistes',
  },
  {
    id: 'sign-a23',
    code: 'A23',
    name: 'Danger aérien',
    meaning: 'Avions à très basse altitude : possible surprise, bruit ou distraction.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-airfield',
    ruleTag: 'Basse altitude',
  },
  {
    id: 'sign-a24',
    code: 'A24',
    name: 'Vent latéral',
    meaning: 'Risque de déport du véhicule, surtout moto, bus, camion et véhicule léger.',
    category: 'danger',
    categoryLabel: 'Danger et vigilance',
    iconType: 'danger-crosswind',
    ruleTag: 'Déport possible',
  },

  // ================= PRIORITE ANNONCEE PAR TRIANGLE =================
  {
    id: 'sign-ab1',
    code: 'AB1',
    name: 'Intersection avec priorité à droite',
    meaning: 'À la prochaine intersection, céder aux véhicules venant de droite.',
    category: 'priority',
    categoryLabel: 'Priorité annoncée',
    iconType: 'priority-cross-right',
    ruleTag: 'Priorité à droite',
  },
  {
    id: 'sign-ab2',
    code: 'AB2',
    name: 'Intersection avec route non prioritaire',
    meaning: 'Vous êtes prioritaire à l’intersection annoncée (les usagers croisés doivent céder).',
    category: 'priority',
    categoryLabel: 'Priorité annoncée',
    iconType: 'priority-road-ahead',
    ruleTag: 'Priorité ponctuelle',
  },
  {
    id: 'sign-ab3a',
    code: 'AB3a',
    name: 'Cédez le passage, signal de position',
    meaning: 'À l’intersection, laisser passer les usagers prioritaires.',
    category: 'priority',
    categoryLabel: 'Priorité annoncée',
    iconType: 'triangle-cedez',
    ruleTag: 'Céder le passage',
  },
  {
    id: 'sign-ab3b',
    code: 'AB3b',
    name: 'Cédez le passage annoncé à l’avance',
    meaning: 'Vous approchez d’un « Cédez le passage » (panneau avancé avec panonceau distance).',
    category: 'priority',
    categoryLabel: 'Priorité annoncée',
    iconType: 'triangle-cedez-advanced',
    ruleTag: 'Annonce cédez le passage',
  },
  {
    id: 'sign-ab4',
    code: 'AB4',
    name: 'STOP, signal de position',
    meaning: 'Arrêt total obligatoire puis céder le passage.',
    category: 'priority',
    categoryLabel: 'Priorité annoncée',
    iconType: 'octogon-stop',
    ruleTag: 'Arrêt total obligatoire',
  },
  {
    id: 'sign-ab5',
    code: 'AB5',
    name: 'STOP annoncé à l’avance',
    meaning: 'Préparez votre arrêt complet au STOP proche (triangle cédez le passage + panonceau STOP 150m).',
    category: 'priority',
    categoryLabel: 'Priorité annoncée',
    iconType: 'triangle-stop-advanced',
    ruleTag: 'Annonce STOP',
  },
  {
    id: 'sign-ab6',
    code: 'AB6',
    name: 'Route prioritaire',
    meaning: 'Vous circulez sur une route qui garde la priorité aux intersections.',
    category: 'priority',
    categoryLabel: 'Priorité annoncée',
    iconType: 'diamond-priority',
    ruleTag: 'Caractère prioritaire',
  },
  {
    id: 'sign-ab7',
    code: 'AB7',
    name: 'Fin de route prioritaire',
    meaning: 'La priorité permanente prend fin : observer les panneaux suivants.',
    category: 'priority',
    categoryLabel: 'Priorité annoncée',
    iconType: 'diamond-priority-end',
    ruleTag: 'Fin de priorité',
  },
  {
    id: 'sign-ab25',
    code: 'AB25',
    name: 'Carrefour à sens giratoire',
    meaning: 'Approche d’un rond-point / giratoire ; respecter la priorité indiquée à l’entrée.',
    category: 'priority',
    categoryLabel: 'Priorité annoncée',
    iconType: 'danger-roundabout',
    ruleTag: 'Sens giratoire',
  },

  // ================= 2. INTERDICTIONS =================
  {
    id: 'sign-b0',
    code: 'B0',
    name: 'Cercle blanc bordé rouge',
    meaning: 'Circulation interdite à tout véhicule dans les deux sens.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-all-traffic',
    ruleTag: 'Circulation interdite 2 sens',
  },
  {
    id: 'sign-b1',
    code: 'B1',
    name: 'Sens interdit',
    meaning: 'Sens interdit : ne jamais entrer dans cette voie dans ce sens.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-entry',
    ruleTag: 'Ne pas entrer',
  },
  {
    id: 'sign-b2a',
    code: 'B2a',
    name: 'Flèche de virage à gauche barrée',
    meaning: 'Interdiction de tourner à gauche à la prochaine intersection.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-left-turn',
    ruleTag: 'Virage gauche interdit',
  },
  {
    id: 'sign-b2b',
    code: 'B2b',
    name: 'Flèche de virage à droite barrée',
    meaning: 'Interdiction de tourner à droite à la prochaine intersection.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-right-turn',
    ruleTag: 'Virage droite interdit',
  },
  {
    id: 'sign-b2c',
    code: 'B2c',
    name: 'Flèche de demi-tour barrée',
    meaning: 'Demi-tour interdit jusqu’à la prochaine intersection.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-u-turn',
    ruleTag: 'Demi-tour interdit',
  },
  {
    id: 'sign-b3',
    code: 'B3',
    name: 'Deux voitures côte à côte',
    meaning: 'Dépassement interdit aux véhicules à moteur (sauf deux-roues sans side-car).',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-overtaking',
    ruleTag: 'Dépassement interdit',
  },
  {
    id: 'sign-b3a',
    code: 'B3a',
    name: 'Camion dépassant barré',
    meaning: 'Dépassement interdit aux poids lourds concernés (> 3.5 t).',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-truck-overtaking',
    ruleTag: 'Poids lourds',
  },
  {
    id: 'sign-b6a1',
    code: 'B6a1',
    name: 'P barré (Stationnement interdit)',
    meaning: 'Stationnement interdit du côté du panneau.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-parking',
    ruleTag: 'Stationnement interdit',
  },
  {
    id: 'sign-b6d',
    code: 'B6d',
    name: 'Croix rouge et bleue',
    meaning: 'Arrêt et stationnement interdits.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-stopping-parking',
    ruleTag: 'Arrêt & stationnement interdits',
  },
  {
    id: 'sign-b7a',
    code: 'B7a',
    name: 'Voiture dans cercle rouge',
    meaning: 'Accès interdit aux véhicules automobiles.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-cars',
    ruleTag: 'Interdit voitures',
  },
  {
    id: 'sign-b7b',
    code: 'B7b',
    name: 'Camion dans cercle rouge',
    meaning: 'Accès interdit aux véhicules de transport de marchandises.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-trucks',
    ruleTag: 'Interdit marchandises',
  },
  {
    id: 'sign-b8',
    code: 'B8',
    name: 'Vélo dans cercle rouge',
    meaning: 'Accès interdit aux cycles.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-bicycles',
    ruleTag: 'Interdit cycles',
  },
  {
    id: 'sign-b9a',
    code: 'B9a',
    name: 'Piéton dans cercle rouge',
    meaning: 'Accès interdit aux piétons.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-pedestrians',
    ruleTag: 'Interdit piétons',
  },
  {
    id: 'sign-b9b',
    code: 'B9b',
    name: 'Motocyclette dans cercle rouge',
    meaning: 'Accès interdit aux motocyclettes.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-motorcycles',
    ruleTag: 'Interdit motos',
  },
  {
    id: 'sign-b10a',
    code: 'B10a',
    name: 'Véhicule agricole',
    meaning: 'Accès interdit aux véhicules agricoles ou engins assimilés.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-tractors',
    ruleTag: 'Interdit tracteurs',
  },
  {
    id: 'sign-b11',
    code: 'B11',
    name: 'Véhicule à traction animale',
    meaning: 'Accès interdit aux charrettes et véhicules à traction animale.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-animal-traction',
    ruleTag: 'Interdit charrettes',
  },
  {
    id: 'sign-b12',
    code: 'B12',
    name: 'Piéton poussant une brouette',
    meaning: 'Accès interdit aux voitures à bras ou véhicules similaires.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-handcarts',
    ruleTag: 'Interdit bras',
  },
  {
    id: 'sign-b13a',
    code: 'B13a',
    name: 'Nombre avec « t » (Tonnage max)',
    meaning: 'Interdiction aux véhicules dépassant le poids total indiqué.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-weight-limit',
    ruleTag: 'Poids total limité',
  },
  {
    id: 'sign-b13b',
    code: 'B13b',
    name: 'Poids par essieu',
    meaning: 'Interdiction aux véhicules dépassant la charge par essieu indiquée.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-axle-load',
    ruleTag: 'Charge par essieu',
  },
  {
    id: 'sign-b14',
    code: 'B14',
    name: 'Nombre dans cercle rouge (ex: 50)',
    meaning: 'Vitesse maximale autorisée : ne pas dépasser la valeur indiquée.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-speed-limit',
    ruleTag: 'Limitation de vitesse',
  },
  {
    id: 'sign-b15',
    code: 'B15',
    name: 'Largeur indiquée',
    meaning: 'Interdiction aux véhicules dépassant la largeur indiquée.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-width-limit',
    ruleTag: 'Largeur max',
  },
  {
    id: 'sign-b16',
    code: 'B16',
    name: 'Hauteur indiquée',
    meaning: 'Interdiction aux véhicules dépassant la hauteur indiquée.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-height-limit',
    ruleTag: 'Hauteur max',
  },
  {
    id: 'sign-b17',
    code: 'B17',
    name: 'Longueur indiquée',
    meaning: 'Interdiction aux véhicules dépassant la longueur indiquée.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-length-limit',
    ruleTag: 'Longueur max',
  },
  {
    id: 'sign-b18a',
    code: 'B18a',
    name: 'Klaxon barré',
    meaning: 'Usage de l’avertisseur sonore interdit, sauf danger immédiat selon les règles locales.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-no-horn',
    ruleTag: 'Avertisseur sonore interdit',
  },
  {
    id: 'sign-b19',
    code: 'B19',
    name: 'Véhicule matières dangereuses',
    meaning: 'Accès interdit aux véhicules transportant certaines matières dangereuses / explosives.',
    category: 'interdiction',
    categoryLabel: 'Interdictions',
    iconType: 'prohibition-hazardous-materials',
    ruleTag: 'Matières dangereuses',
  },

  // ================= FIN D'INTERDICTION =================
  {
    id: 'sign-b33',
    code: 'B33',
    name: 'Fin de limitation de vitesse',
    meaning: 'La limite spécifique indiquée par le précédent panneau prend fin ; appliquer la règle générale de la route.',
    category: 'fin_interdiction',
    categoryLabel: 'Fin d’interdiction',
    iconType: 'end-speed-limit',
    ruleTag: 'Règle générale',
  },
  {
    id: 'sign-b34',
    code: 'B34',
    name: 'Fin d’interdiction de dépasser',
    meaning: 'Le dépassement redevient possible seulement si les conditions sont sûres.',
    category: 'fin_interdiction',
    categoryLabel: 'Fin d’interdiction',
    iconType: 'end-overtaking',
    ruleTag: 'Dépassement possible',
  },
  {
    id: 'sign-b35',
    code: 'B35',
    name: 'Fin d’interdiction de klaxonner',
    meaning: 'L’interdiction spécifique de l’avertisseur sonore prend fin.',
    category: 'fin_interdiction',
    categoryLabel: 'Fin d’interdiction',
    iconType: 'end-horn',
    ruleTag: 'Fin interdiction klaxon',
  },
  {
    id: 'sign-b31',
    code: 'B31',
    name: 'Fin de toutes interdictions précédemment signalées',
    meaning: 'Les interdictions imposées par les panneaux antérieurs prennent fin, sauf règle générale contraire.',
    category: 'fin_interdiction',
    categoryLabel: 'Fin d’interdiction',
    iconType: 'end-all-restrictions',
    ruleTag: 'Fin toutes interdictions',
  },

  // ================= 3. OBLIGATIONS =================
  {
    id: 'sign-b21-1',
    code: 'B21-1',
    name: 'Flèche blanche vers la droite',
    meaning: 'Tourner obligatoirement à droite avant le panneau.',
    category: 'obligation',
    categoryLabel: 'Obligations',
    iconType: 'obligation-right-before',
    ruleTag: 'Tourner à droite',
  },
  {
    id: 'sign-b21-2',
    code: 'B21-2',
    name: 'Flèche blanche vers la gauche',
    meaning: 'Tourner obligatoirement à gauche avant le panneau.',
    category: 'obligation',
    categoryLabel: 'Obligations',
    iconType: 'obligation-left-before',
    ruleTag: 'Tourner à gauche',
  },
  {
    id: 'sign-b21a',
    code: 'B21a',
    name: 'Flèche vers le haut',
    meaning: 'Aller obligatoirement tout droit.',
    category: 'obligation',
    categoryLabel: 'Obligations',
    iconType: 'obligation-straight',
    ruleTag: 'Tout droit',
  },
  {
    id: 'sign-b21b',
    code: 'B21b',
    name: 'Flèches tout droit + droite',
    meaning: 'Aller tout droit ou tourner à droite seulement.',
    category: 'obligation',
    categoryLabel: 'Obligations',
    iconType: 'obligation-straight-right',
    ruleTag: 'Tout droit ou droite',
  },
  {
    id: 'sign-b21c',
    code: 'B21c',
    name: 'Flèches tout droit + gauche',
    meaning: 'Aller tout droit ou tourner à gauche seulement.',
    category: 'obligation',
    categoryLabel: 'Obligations',
    iconType: 'obligation-straight-left',
    ruleTag: 'Tout droit ou gauche',
  },
  {
    id: 'sign-b21d',
    code: 'B21d',
    name: 'Flèches droite + gauche',
    meaning: 'Tourner obligatoirement à droite ou à gauche ; tout droit interdit.',
    category: 'obligation',
    categoryLabel: 'Obligations',
    iconType: 'obligation-left-right',
    ruleTag: 'Droite ou gauche',
  },
  {
    id: 'sign-b21e',
    code: 'B21e',
    name: 'Flèches en cercle',
    meaning: 'Sens giratoire obligatoire : suivre le rond-point.',
    category: 'obligation',
    categoryLabel: 'Obligations',
    iconType: 'obligation-roundabout',
    ruleTag: 'Giratoire obligatoire',
  },
  {
    id: 'sign-b21f',
    code: 'B21f',
    name: 'Flèche oblique descendante à droite',
    meaning: 'Contourner l’obstacle par la droite.',
    category: 'obligation',
    categoryLabel: 'Obligations',
    iconType: 'obligation-pass-right',
    ruleTag: 'Contournement droite',
  },
  {
    id: 'sign-b21g',
    code: 'B21g',
    name: 'Flèche oblique descendante à gauche',
    meaning: 'Contourner l’obstacle par la gauche.',
    category: 'obligation',
    categoryLabel: 'Obligations',
    iconType: 'obligation-pass-left',
    ruleTag: 'Contournement gauche',
  },
  {
    id: 'sign-b22a',
    code: 'B22a',
    name: 'Vélo blanc sur fond bleu',
    meaning: 'Piste ou bande obligatoire pour les cycles.',
    category: 'obligation',
    categoryLabel: 'Obligations',
    iconType: 'obligation-bicycle-path',
    ruleTag: 'Piste cyclable',
  },
  {
    id: 'sign-b22b',
    code: 'B22b',
    name: 'Piéton blanc sur fond bleu',
    meaning: 'Chemin obligatoire pour les piétons.',
    category: 'obligation',
    categoryLabel: 'Obligations',
    iconType: 'obligation-pedestrian-path',
    ruleTag: 'Chemin piéton',
  },
  {
    id: 'sign-b22c',
    code: 'B22c',
    name: 'Piéton et vélo séparés',
    meaning: 'Voie obligatoire séparée pour piétons et cyclistes.',
    category: 'obligation',
    categoryLabel: 'Obligations',
    iconType: 'obligation-segregated-path',
    ruleTag: 'Voies séparées',
  },
  {
    id: 'sign-b22d',
    code: 'B22d',
    name: 'Piéton et vélo ensemble',
    meaning: 'Voie obligatoire commune aux piétons et cyclistes.',
    category: 'obligation',
    categoryLabel: 'Obligations',
    iconType: 'obligation-shared-path',
    ruleTag: 'Voie commune',
  },
  {
    id: 'sign-b25',
    code: 'B25',
    name: 'Chaînes sur pneus',
    meaning: 'Chaînes ou équipements antidérapants obligatoires selon la zone et la période.',
    category: 'obligation',
    categoryLabel: 'Obligations',
    iconType: 'obligation-snow-chains',
    ruleTag: 'Équipements spéciaux',
  },
  {
    id: 'sign-b26',
    code: 'B26',
    name: 'Vitesse minimale dans cercle bleu (ex: 30)',
    meaning: 'Ne pas circuler sous la vitesse indiquée, lorsque les conditions permettent de la respecter.',
    category: 'obligation',
    categoryLabel: 'Obligations',
    iconType: 'obligation-min-speed',
    ruleTag: 'Vitesse minimale',
  },

  // ================= FIN D'OBLIGATION =================
  {
    id: 'sign-b40',
    code: 'B40',
    name: 'Fin de piste obligatoire pour cycles',
    meaning: 'Les cyclistes ne sont plus obligés d’utiliser la piste signalée.',
    category: 'fin_obligation',
    categoryLabel: 'Fin d’obligation',
    iconType: 'end-bicycle-path',
    ruleTag: 'Fin obligation cycles',
  },
  {
    id: 'sign-b41',
    code: 'B41',
    name: 'Fin de chemin obligatoire pour piétons',
    meaning: 'La voie réservée obligatoire aux piétons se termine.',
    category: 'fin_obligation',
    categoryLabel: 'Fin d’obligation',
    iconType: 'end-pedestrian-path',
    ruleTag: 'Fin voie piétonne',
  },
  {
    id: 'sign-b43',
    code: 'B43',
    name: 'Fin de vitesse minimale obligatoire',
    meaning: 'La vitesse minimale imposée cesse.',
    category: 'fin_obligation',
    categoryLabel: 'Fin d’obligation',
    iconType: 'end-min-speed',
    ruleTag: 'Fin vitesse mini',
  },
  {
    id: 'sign-b44',
    code: 'B44',
    name: 'Fin d’équipements spéciaux obligatoires',
    meaning: 'Les chaînes ou équipements imposés ne sont plus obligatoires à partir de là.',
    category: 'fin_obligation',
    categoryLabel: 'Fin d’obligation',
    iconType: 'end-snow-chains',
    ruleTag: 'Fin chaînes',
  },

  // ================= 4. INDICATIONS ET SERVICES =================
  {
    id: 'sign-c1a',
    code: 'C1a',
    name: 'Lettre P blanche sur bleu',
    meaning: 'Lieu aménagé pour le stationnement.',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-parking',
    ruleTag: 'Parking',
  },
  {
    id: 'sign-c1b',
    code: 'C1b',
    name: 'P avec disque ou horloge',
    meaning: 'Stationnement gratuit mais limité dans le temps, avec contrôle (zone bleue).',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-parking-disk',
    ruleTag: 'Zone bleue / disque',
  },
  {
    id: 'sign-c1c',
    code: 'C1c',
    name: 'P avec indication de paiement',
    meaning: 'Stationnement payant.',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-parking-paid',
    ruleTag: 'Stationnement payant',
  },
  {
    id: 'sign-c5',
    code: 'C5',
    name: 'Taxi sur fond bleu',
    meaning: 'Station de taxis ; arrêt et stationnement réservés aux taxis en service.',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-taxi',
    ruleTag: 'Station de taxis',
  },
  {
    id: 'sign-c6',
    code: 'C6',
    name: 'Autobus sur fond bleu',
    meaning: 'Arrêt d’autobus ; les autres véhicules ne doivent pas y stationner.',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-bus-stop',
    ruleTag: 'Arrêt de bus',
  },
  {
    id: 'sign-c8',
    code: 'C8',
    name: 'Refuge / arrêt d’urgence',
    meaning: 'Emplacement réservé uniquement aux arrêts d’urgence.',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-emergency-refuge',
    ruleTag: 'Arrêt d’urgence',
  },
  {
    id: 'sign-c12',
    code: 'C12',
    name: 'Flèche blanche sur fond bleu',
    meaning: 'Circulation à sens unique.',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-one-way',
    ruleTag: 'Sens unique',
  },
  {
    id: 'sign-id2',
    code: 'ID2',
    name: 'Avion',
    meaning: 'Direction ou proximité d’un aéroport.',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-airport',
    ruleTag: 'Aéroport',
  },
  {
    id: 'sign-id3',
    code: 'ID3',
    name: 'Hôpital avec urgences',
    meaning: 'Hôpital ou clinique assurant un service d’urgence.',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-hospital-emergency',
    ruleTag: 'Urgences médicales',
  },
  {
    id: 'sign-id4',
    code: 'ID4',
    name: 'Hôpital sans urgences',
    meaning: 'Hôpital ou clinique ne recevant pas les urgences.',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-hospital-standard',
    ruleTag: 'Établissement de soins',
  },
  {
    id: 'sign-id5b',
    code: 'ID5b',
    name: 'Téléphone',
    meaning: 'Poste d’appel téléphonique ou appel de secours.',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-phone',
    ruleTag: 'Poste de secours',
  },
  {
    id: 'sign-id7',
    code: 'ID7',
    name: 'Symbole fauteuil roulant',
    meaning: 'Installation accessible aux personnes à mobilité réduite.',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-disabled',
    ruleTag: 'PMR',
  },
  {
    id: 'sign-id10',
    code: 'ID10',
    name: 'Auberge de jeunesse',
    meaning: 'Hébergement de type auberge.',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-youth-hostel',
    ruleTag: 'Auberge',
  },
  {
    id: 'sign-id13b',
    code: 'ID13b',
    name: 'Bateau / port',
    meaning: 'Port de commerce ou installation portuaire.',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-port',
    ruleTag: 'Port maritime / fluvial',
  },
  {
    id: 'sign-id25',
    code: 'ID25',
    name: 'Lit',
    meaning: 'Hôtel ou hébergement.',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-hotel',
    ruleTag: 'Hôtel',
  },
  {
    id: 'sign-id26a',
    code: 'ID26a',
    name: 'Couverts',
    meaning: 'Restaurant ouvert tous les jours.',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-restaurant',
    ruleTag: 'Restaurant',
  },
  {
    id: 'sign-id26b',
    code: 'ID26b',
    name: 'Verre / collation',
    meaning: 'Débit de boissons ou lieu de restauration légère.',
    category: 'indication',
    categoryLabel: 'Indications et services',
    iconType: 'indication-cafe',
    ruleTag: 'Café / Collation',
  },

  // ================= BALISES ET EQUIPEMENTS =================
  {
    id: 'sign-j1',
    code: 'J1',
    name: 'Chevrons de virage',
    meaning: 'Matérialise et guide dans un virage.',
    category: 'balise',
    categoryLabel: 'Balises et équipements',
    iconType: 'beacon-curve-chevron',
    ruleTag: 'Guidage virage',
  },
  {
    id: 'sign-j3',
    code: 'J3',
    name: 'Balise d’intersection',
    meaning: 'Aide à repérer la position d’une intersection.',
    category: 'balise',
    categoryLabel: 'Balises et équipements',
    iconType: 'beacon-intersection',
    ruleTag: 'Intersection',
  },
  {
    id: 'sign-j4',
    code: 'J4',
    name: 'Balisage de virage',
    meaning: 'Rend le tracé d’un virage plus visible, notamment de nuit.',
    category: 'balise',
    categoryLabel: 'Balises et équipements',
    iconType: 'beacon-curve-white',
    ruleTag: 'Visibilité nocturne',
  },
  {
    id: 'sign-j5',
    code: 'J5',
    name: 'Tête d’îlot directionnel',
    meaning: 'Obstacle à contourner par la droite selon le sens de la flèche.',
    category: 'balise',
    categoryLabel: 'Balises et équipements',
    iconType: 'beacon-island',
    ruleTag: 'Contournement îlot',
  },
  {
    id: 'sign-j6',
    code: 'J6',
    name: 'Délinéateur',
    meaning: 'Balise les limites de chaussée.',
    category: 'balise',
    categoryLabel: 'Balises et équipements',
    iconType: 'beacon-delineator',
    ruleTag: 'Bord de chaussée',
  },
  {
    id: 'sign-j7',
    code: 'J7',
    name: 'Manche à air',
    meaning: 'Signale un vent latéral fréquent et en indique la direction/intensité.',
    category: 'balise',
    categoryLabel: 'Balises et équipements',
    iconType: 'beacon-windsock',
    ruleTag: 'Vent latéral',
  },
  {
    id: 'sign-j10',
    code: 'J10',
    name: 'Balise de passage à niveau',
    meaning: 'Avertit et guide à l’approche d’un passage à niveau (3, 2 ou 1 bande rouge selon la distance).',
    category: 'balise',
    categoryLabel: 'Balises et équipements',
    iconType: 'beacon-level-crossing',
    ruleTag: 'Distance PN',
  },

  // ================= 5. PASSAGES A NIVEAU =================
  {
    id: 'sign-g1',
    code: 'G1',
    name: 'Croix de Saint-André',
    meaning: 'Passage à niveau à une voie, sans barrières ou demi-barrières.',
    category: 'passage_niveau',
    categoryLabel: 'Passages à niveau',
    iconType: 'rail-saint-andrew-single',
    ruleTag: 'PN 1 voie',
  },
  {
    id: 'sign-g1a',
    code: 'G1a',
    name: 'Double croix de Saint-André',
    meaning: 'Passage à niveau à plusieurs voies.',
    category: 'passage_niveau',
    categoryLabel: 'Passages à niveau',
    iconType: 'rail-saint-andrew-multi',
    ruleTag: 'PN multi-voies',
  },
  {
    id: 'sign-g1bis',
    code: 'G1 bis / G1a bis',
    name: 'Croix avec signal automatique',
    meaning: 'Passage à niveau équipé de feux et alarme sonore.',
    category: 'passage_niveau',
    categoryLabel: 'Passages à niveau',
    iconType: 'rail-automatic-signal',
    ruleTag: 'Feux & sonnerie PN',
  },
  {
    id: 'sign-g2',
    code: 'G2',
    name: 'Feu rouge clignotant + demi-barrières',
    meaning: 'Arrêt obligatoire ; le train approche ou les barrières vont se fermer.',
    category: 'passage_niveau',
    categoryLabel: 'Passages à niveau',
    iconType: 'rail-flashing-red-barrier',
    ruleTag: 'Arrêt absolu',
  },
  {
    id: 'sign-r24',
    code: 'R24',
    name: 'Signal d’arrêt ferroviaire',
    meaning: 'Arrêt exigé avant le franchissement selon le dispositif installé.',
    category: 'passage_niveau',
    categoryLabel: 'Passages à niveau',
    iconType: 'rail-stop-signal',
    ruleTag: 'Arrêt exigé',
  },

  // ================= SIGNALISATION TEMPORAIRE =================
  {
    id: 'sign-temp-travaux',
    code: 'AK5',
    name: 'Panneau « Travaux »',
    meaning: 'Zone de chantier : ralentir, augmenter les distances et surveiller les ouvriers.',
    category: 'temporaire',
    categoryLabel: 'Signalisation temporaire',
    iconType: 'temp-roadworks',
    ruleTag: 'Zone de chantier',
  },
  {
    id: 'sign-temp-narrow',
    code: 'AK3',
    name: 'Rétrécissement temporaire',
    meaning: 'Voies réduites ou déviées : respecter les priorités temporaires.',
    category: 'temporaire',
    categoryLabel: 'Signalisation temporaire',
    iconType: 'temp-narrow',
    ruleTag: 'Voies réduites',
  },
  {
    id: 'sign-temp-altern',
    code: 'K2',
    name: 'Circulation alternée',
    meaning: 'Un seul sens passe à la fois : obéir au feu de chantier ou à l’agent.',
    category: 'temporaire',
    categoryLabel: 'Signalisation temporaire',
    iconType: 'temp-alternate',
    ruleTag: 'Alternat de chantier',
  },
  {
    id: 'sign-temp-deviation',
    code: 'KD22',
    name: 'Déviation',
    meaning: 'Suivre les flèches ou panneaux jaunes, même si le trajet habituel est différent.',
    category: 'temporaire',
    categoryLabel: 'Signalisation temporaire',
    iconType: 'temp-detour',
    ruleTag: 'Itinéraire de déviation',
  },
  {
    id: 'sign-temp-vitesse',
    code: 'BK14',
    name: 'Limitation temporaire',
    meaning: 'Respecter la vitesse affichée jusqu’à la fin de la zone signalée.',
    category: 'temporaire',
    categoryLabel: 'Signalisation temporaire',
    iconType: 'temp-speed',
    ruleTag: 'Vitesse temporaire',
  },
  {
    id: 'sign-temp-cones',
    code: 'K5a',
    name: 'Cônes et barrières de chantier',
    meaning: 'Ne pas les franchir ni stationner dans la zone protégée.',
    category: 'temporaire',
    categoryLabel: 'Signalisation temporaire',
    iconType: 'temp-cones',
    ruleTag: 'Zone balisée',
  },

  // ================= PANONCEAUX =================
  {
    id: 'pan-distance',
    name: 'Panonceau de Distance (ex: « 150 m »)',
    meaning: 'Le danger ou la règle commence 150 m plus loin.',
    category: 'panonceau',
    categoryLabel: 'Panonceaux',
    iconType: 'panonceau-distance',
    ruleTag: 'Distance d’application',
  },
  {
    id: 'pan-etendue',
    name: 'Panonceau d’Étendue (ex: « Sur 2 km »)',
    meaning: 'La règle ou le danger s’applique pendant toute la longueur indiquée.',
    category: 'panonceau',
    categoryLabel: 'Panonceaux',
    iconType: 'panonceau-extent',
    ruleTag: 'Longueur de la zone',
  },
  {
    id: 'pan-fleche-haut',
    name: 'Flèche vers le haut (sous panneau)',
    meaning: 'La règle s’applique après le panneau.',
    category: 'panonceau',
    categoryLabel: 'Panonceaux',
    iconType: 'panonceau-arrow-up',
    ruleTag: 'Début zone',
  },
  {
    id: 'pan-fleche-bas',
    name: 'Flèche vers le bas (sous panneau)',
    meaning: 'La règle se termine au panneau.',
    category: 'panonceau',
    categoryLabel: 'Panonceaux',
    iconType: 'panonceau-arrow-down',
    ruleTag: 'Fin zone',
  },
  {
    id: 'pan-double-fleche',
    name: 'Double flèche haut/bas',
    meaning: 'La règle s’applique de part et d’autre ou sur une zone en rappel.',
    category: 'panonceau',
    categoryLabel: 'Panonceaux',
    iconType: 'panonceau-double-arrow',
    ruleTag: 'Rappel / zone',
  },
  {
    id: 'pan-horaire',
    name: 'Panonceau Horaire (ex: « 7 h – 19 h »)',
    meaning: 'La règle ne s’applique qu’aux heures indiquées.',
    category: 'panonceau',
    categoryLabel: 'Panonceaux',
    iconType: 'panonceau-schedule',
    ruleTag: 'Plage horaire',
  },
  {
    id: 'pan-categorie',
    name: 'Catégorie de véhicule (Camion, moto, taxi, bus)',
    meaning: 'La règle vise seulement le véhicule représenté.',
    category: 'panonceau',
    categoryLabel: 'Panonceaux',
    iconType: 'panonceau-vehicle-category',
    ruleTag: 'Usagers ciblés',
  },
  {
    id: 'pan-sauf',
    name: 'Panonceau « Sauf… » (riverains, taxis)',
    meaning: 'Les usagers cités bénéficient d’une exception et ne sont pas soumis à la restriction.',
    category: 'panonceau',
    categoryLabel: 'Panonceaux',
    iconType: 'panonceau-except',
    ruleTag: 'Dérogation',
  },
  {
    id: 'pan-pluie',
    name: 'Sol humide / Symbole pluie',
    meaning: 'Le danger est particulièrement présent lorsqu’il pleut ou par chaussée mouillée.',
    category: 'panonceau',
    categoryLabel: 'Panonceaux',
    iconType: 'panonceau-wet-road',
    ruleTag: 'Conditions météo',
  },
  {
    id: 'pan-schema',
    name: 'Schéma d’intersection',
    meaning: 'Explique la branche de route prioritaire (trait épais) et les routes secondaires (traits fins).',
    category: 'panonceau',
    categoryLabel: 'Panonceaux',
    iconType: 'panonceau-intersection-scheme',
    ruleTag: 'Branche prioritaire',
  },
];

export const EXAM_METHOD_TIPS: string[] = [
  'Regarde d’abord la forme du panneau.',
  'Lis ensuite la couleur : rouge = interdiction/danger, bleu = obligation ou information.',
  'Identifie le pictogramme : piéton, camion, voiture, flèche, chiffre, train, animal…',
  'Lis toujours le panonceau situé en dessous.',
  'En cas de travaux ou de panneaux jaunes, suis la signalisation temporaire.',
  'À l’approche d’un STOP, l’arrêt doit être total, même si aucune voiture n’arrive.',
  'À l’approche d’un « Cédez le passage », ralentis et ne t’engages que sans gêner les autres usagers.',
  'Le Code CEMAC s’applique aux usagers, conducteurs et véhicules qui circulent dans les États membres, y compris le Cameroun ; pour préparer une épreuve locale, retiens surtout la signalisation réellement enseignée par ton auto-école et visible sur les routes de Yaoundé ou de ta ville.',
];
