import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'fr' | 'en';

export const translations = {
  fr: {
    // General & Platform
    appName: 'Matoa',
    platformSubtitle: 'SaaS Auto-Écoles',
    platformSubtitleLong: 'Plateforme SaaS Multi-Tenant réservée aux Auto-Écoles',
    platformAdminBadge: 'Plateforme SaaS Admin',
    copyrightFooter: 'Matoa SaaS © 2026 — Plateforme sécurisée de formation auto-école.',
    logout: 'Déconnexion',
    language: 'Langue',
    themeLight: 'Mode Clair',
    themeDark: 'Mode Sombre',
    switchThemeToLight: 'Basculer en mode clair',
    switchThemeToDark: 'Basculer en mode sombre',
    loading: 'Chargement...',
    save: 'Enregistrer',
    saving: 'Enregistrement...',
    cancel: 'Annuler',
    close: 'Fermer',
    delete: 'Supprimer',
    edit: 'Modifier',
    actions: 'Actions',
    status: 'Statut',
    progress: 'Progression',
    codeUnique: 'Code Unique',
    name: 'Nom',
    fullName: 'Nom Complet',
    email: 'Email',
    phone: 'Téléphone',
    address: 'Adresse Physique',
    startDate: 'Date Début',
    endDate: 'Date Fin',
    details: 'Détails',
    confirm: 'Confirmer',
    yes: 'Oui',
    no: 'Non',
    errorOccurred: 'Une erreur est survenue.',
    search: 'Rechercher',
    searchPlaceholder: 'Rechercher un élève, email, code...',
    searchLogsPlaceholder: 'Rechercher dans les logs...',
    refresh: 'Actualiser',
    fullscreen: 'Plein Écran',
    normalScreen: 'Normal',
    exitFullscreen: 'Quitter Plein Écran',

    // Roles
    roleSuperAdmin: 'Super Admin',
    roleAutoEcole: 'Admin Auto-École',
    roleEleve: 'Élève',
    roleLabel: 'Rôle sur Matoa :',

    // Statuses
    active: 'Actif',
    operational: 'Opérationnel',
    blocked: 'Bloqué',
    suspended: 'Suspendu',
    expired: 'Expiré',
    completed: 'Certifié',
    valid: 'Valide',
    accessValid: 'Accès Valide',
    notStarted: 'Non commencé',
    inProgress: 'En cours',
    locked: 'Verrouillé',
    available: 'Disponible',
    validated: 'Validé',

    // Exports
    exportPdf: 'Exporter en PDF',
    exportExcel: 'Exporter en Excel (CSV)',
    exportStats: 'Exporter les Statistiques',
    exportStudentsList: 'Exporter la Liste des Élèves',
    exportCsv: 'Export CSV',
    exportJson: 'Export JSON',
    exportCsvStudents: 'CSV Élèves',
    exportCsvCourses: 'CSV Cours',
    exportPdfReport: 'Rapport PDF',
    globalNetworkReport: 'Rapport Global Réseau Matoa',

    // Login Page
    loginStudentTab: 'Élève',
    loginSchoolTab: 'Auto-École',
    loginAdminTab: 'Super Admin',
    loginAutoEcoleCode: 'Code Unique Auto-École *',
    loginAutoEcoleCodePlaceholder: 'MATOA-AE-...',
    loginAutoEcoleCodeHint: 'Fourni par votre auto-école lors de votre inscription.',
    loginStudentCodeOrEmail: 'Code Élève (ou Email) *',
    loginStudentCodePlaceholder: 'Entrez votre code élève ou email',
    loginEmailProfessional: 'Adresse Email Professionnelle *',
    loginPassword: 'Mot de passe *',
    loginConnecting: 'Connexion en cours...',
    loginSubmit: 'Se connecter à mon espace',
    loginSuspendedTitle: '⛔ ACCÈS COMPTE SUSPENDU',

    // Header Navbar & Settings
    accountSettings: 'Paramètres du Compte',
    accountSettingsSubtitle: 'Gérez vos informations personnelles et préférences',
    tabPersonalProfile: 'Profil Personnel',
    tabSecurityPassword: 'Sécurité & Mot de Passe',
    tabNotifications: 'Notifications',
    currentPassword: 'Mot de passe actuel',
    newPassword: 'Nouveau mot de passe',
    newPasswordPlaceholder: 'Minimum 6 caractères',
    confirmNewPassword: 'Confirmer le nouveau mot de passe',
    confirmPasswordPlaceholder: 'Répétez le nouveau mot de passe',
    notifUnlockModules: 'Déblocage de Nouveaux Modules',
    notifUnlockModulesDesc: 'Recevoir un email quand un module est déverrouillé',
    notifQuizResults: 'Résultats des Quiz & Certificats',
    notifQuizResultsDesc: 'Confirmation par email lors de la réussite des quiz',
    notifExpiryReminder: 'Rappel Expiration Formation',
    notifExpiryReminderDesc: 'Alertes 15 jours avant la date de fin de validité',
    notifSms: 'Notifications SMS',
    notifSmsDesc: 'Alerte directe sur mobile (optionnel)',
    settingsUpdatedSuccess: 'Vos paramètres ont été mis à jour avec succès.',
    passwordRequiredError: 'Veuillez saisir un nouveau mot de passe.',
    passwordMismatchError: 'Les nouveaux mots de passe ne correspondent pas.',

    // Super Admin Dashboard
    superAdminDashboardTitle: 'Tableau de Bord Super Admin Matoa',
    superAdminDashboardSubtitle: 'Supervision globale du parc auto-écoles, gestion des modules théoriques et audit des logs.',
    createSchoolBtn: 'Créer une Auto-École',
    createModuleBtn: 'Créer un Module',
    tabOverview: 'Vue d\'Ensemble',
    tabSchoolsFleet: 'Parc Auto-Écoles',
    tabLicencePrograms: 'Programmes Permis',
    tabModulesAndQuizzes: 'Modules & Quiz',
    tabActivityLogs: 'Journal d\'Activité Globale',
    totalSchools: 'Total Auto-Écoles',
    activeSchoolsCount: 'établissement(s) actif(s)',
    totalStudentsRegistered: 'Total Élèves Inscrits',
    acrossAllSchools: 'Sur l\'ensemble des établissements',
    averageProgress: 'Progression Moyenne',
    studentsCodeProgress: 'Avancement des élèves au Code',
    certificatesEarned: 'Certificats Décrochés',
    fullCompletedTrainings: 'Formations 100% complétées',
    enrollmentAndCertTrends: 'Tendances d\'Inscriptions & Certifications',
    monthlyNetworkEvolution: 'Évolution mensuelle globale sur le réseau',
    inscriptionsLegend: 'Inscriptions',
    certificationsLegend: 'Certifications',
    progressBreakdown: 'Répartition de la Progression',
    progressDistributionRanges: 'Répartition par tranches d\'avancement',
    moduleSuccessRate: 'Taux de Validation des Modules Théoriques',
    moduleSuccessRateSub: 'Pourcentage d\'élèves ayant réussi chaque module',
    successRate: 'Taux de réussite',
    recentPartnerSchools: 'Auto-Écoles Partenaires Récentes',
    schoolNameTh: 'Nom Établissement',
    schoolCodeTh: 'Code AE Unique',
    contactTh: 'Contact',
    studentsEnrolledTh: 'Élèves Inscrits',
    suspendBtn: 'Suspendre',
    activateBtn: 'Activer',
    manageSchoolsFleetTitle: 'Gestion du Parc des Auto-Écoles',
    newSchoolBtn: 'Nouvelle Auto-École',
    noSloganFallback: 'Sans slogan spécifique.',
    adminContactEmail: 'Email Contact Admin :',
    phoneLabel: 'Téléphone :',
    notProvided: 'Non renseigné',
    studentsCountLabel: 'Élèves enregistrés :',
    themeLabel: 'Thème :',
    primaryColor: 'Primaire',
    secondaryColor: 'Secondaire',
    deleteSchoolConfirmTitle: 'Supprimer l\'Auto-École ?',
    deleteSchoolConfirmWarning: 'Attention : Cette action est irréversible. La suppression de cet établissement entraînera la suppression définitive de tous les comptes élèves associés ainsi que l\'historique d\'activité de ce tenant.',
    confirmDelete: 'Confirmer la Suppression',
    licenceProgramsTitle: 'Programmes de Formation par Type de Permis',
    licenceProgramsSubtitle: 'Créez et personnalisez les parcours pédagogiques dédiés selon la catégorie du permis (A, B, C, D, etc.).',
    newProgramBtn: 'Nouveau Programme Permis',
    noProgramDefined: 'Aucun programme de permis défini',
    noProgramDefinedHelp: 'Cliquez sur "Nouveau Programme Permis" pour associer des modules à chaque catégorie de permis.',
    modulesIncludedInProgram: 'Modules inclus dans ce programme :',
    allActiveModules: 'Tous les modules actifs',
    theoreticalModulesTitle: 'Modules de Formation Théorique',
    theoreticalModulesSubtitle: 'Chaque module comprend un résumé, N leçons (avec mini-quiz de 5 questions après chaque leçon) et un quiz de fin de module (10 questions).',
    resetPermisBBtn: 'Réinitialiser Permis B (10 Modules)',
    newModuleBtn: 'Nouveau Module',
    orderPrefix: 'Ordre',
    lessonsChip: 'Leçon(s)',
    quizEndChip: 'Quiz Fin :',
    minScoreChip: 'Score min :',
    manageLessonsAndMiniQuiz: 'Gérer Leçons & Mini-Quiz (5Q)',
    finalModuleQuizAction: 'Quiz Fin de Module',
    globalLogsTitle: 'Journal d\'Activité de la Plateforme',
    userFallback: 'Utilisateur',

    // Modals in SuperAdmin
    createSchoolModalTitle: 'Inscrire une Nouvelle Auto-École',
    schoolNameRequired: 'Nom de l\'établissement *',
    schoolNamePlaceholder: 'Ex: Auto-École Conduite Passion',
    physicalAddress: 'Adresse Physique',
    physicalAddressPlaceholder: 'Ex: 15 Boulevard Haussmann, Paris',
    adminEmailRequired: 'Email Admin *',
    initialPasswordRequired: 'Mot de passe initial *',
    primaryColorLabel: 'Couleur Primaire',
    secondaryColorLabel: 'Couleur Secondaire',
    sloganLabel: 'Slogan',
    sloganPlaceholder: 'Slogan d\'accueil...',
    createAndGenerateCode: 'Créer et Générer Code AE',
    editSchoolModalTitle: 'Modifier l\'Auto-École —',
    contactEmail: 'Email Contact',
    logoUrlLabel: 'URL du Logo',
    updateSchoolBtn: 'Mettre à jour l\'Auto-École',
    createModuleModalTitle: 'Nouveau Module de Formation Théorique',
    editModuleModalTitle: 'Éditer le Module de Formation',
    moduleTitleRequired: 'Titre du Module *',
    moduleTitlePlaceholder: 'Ex: Module 4 : Les Feux et l\'Éclairage',
    moduleDescLabel: 'Description',
    moduleDescPlaceholder: 'Contenu synthétique du cours...',
    videoUrlRequired: 'URL de la Vidéo MP4 *',
    durationSeconds: 'Durée (sec)',
    minWatchSeconds: 'Min Visionnage (sec)',
    minQuizPct: 'Min Quiz (%)',
    saveModuleBtn: 'Enregistrer Module',
    moduleQuizModalBadge: 'Quiz de Fin de Module (10 Questions)',
    moduleQuizModalTitle: 'Édition du Quiz —',
    quizChronoSeconds: 'Chrono du Quiz Final (secondes)',
    totalQuestionsCount: 'Total Questions :',
    generate10QuestionsBtn: 'Générer 10 Questions',
    questionIndex: 'Question',
    questionTextPlaceholder: 'Intitulé de la question...',
    answerOptionsPrompt: 'Options de réponse (Cocher la bonne réponse) :',
    pedagogicalExplanation: 'Explication pédagogique :',
    explanationPlaceholder: 'Explication affichée après le choix...',
    addQuestionToQuiz: '+ Ajouter une question au Quiz',
    saveFinalQuizBtn: 'Enregistrer Quiz Final (10Q)',
    lessonsModalBadge: 'Structure du Module : N Leçons & Mini-Quiz (5Q)',
    lessonsModalTitle: 'Gestion des Leçons —',
    lessonIndex: 'Leçon',
    deleteLessonBtn: 'Supprimer la Leçon',
    lessonTitleLabel: 'Titre de la Leçon',
    lessonTitlePlaceholder: 'Titre de la leçon...',
    lessonSummaryLabel: 'Résumé / Description de la Leçon',
    lessonSummaryPlaceholder: 'Court résumé de cette leçon...',
    lessonVideoUrlLabel: 'URL de la Vidéo',
    activateMiniQuizCheckbox: 'Activer le Mini-Quiz de 5 questions après cette leçon',
    generate5MiniQuizBtn: 'Générer 5 Questions de Mini-Quiz',
    miniQuizQuestionsHeader: 'Questions du Mini-Quiz (5 recommandées) :',
    deleteQuestionBtn: 'Supprimer Q',
    addQuestionToMiniQuiz: '+ Ajouter une question au mini-quiz',
    addLessonToModule: '+ Ajouter une Leçon au Module',
    saveLessonsAndMiniQuizBtn: 'Enregistrer les Leçons & Mini-Quiz',
    newProgramModalTitle: 'Nouveau Programme Permis',
    editProgramModalTitle: 'Modifier le Programme Permis',
    programSubtitle: 'Définissez la catégorie de permis et les modules de formation applicables.',
    categoryPermisLabel: 'Catégorie / Type de Permis *',
    permisBOption: 'Permis B (Voiture / Véhicule léger)',
    programTitleRequired: 'Titre du Programme *',
    programTitlePlaceholder: 'ex. Programme Permis B - Conduite Automobile',
    programDescAndGoals: 'Description & Objectifs du Programme',
    programDescPlaceholder: 'Objectifs pédagogiques et règles de la formation...',
    selectModulesToInclude: 'Sélectionnez les Modules à inclure dans ce Programme :',
    saveProgramBtn: 'Enregistrer le Programme',

    // Auto-Ecole Dashboard
    schoolCodeBadge: 'Code Unique :',
    schoolDefaultSlogan: 'Plateforme d\'apprentissage théorique du Code de la Route',
    quickSearchPlaceholder: 'Recherche rapide élève (Nom, Code MATOA-EL-..., Email, Tél)...',
    clearSearchTitle: 'Effacer la recherche',
    foundRecords: 'Dossiers trouvés',
    closeDropdown: 'Fermer ✕',
    noStudentFoundFor: 'Aucun dossier élève correspondant à',
    permisPrefix: 'Permis',
    trackingBtn: 'Suivi',
    editBtn: 'Éditer',
    tabBranding: 'Branding & Thème',
    tabStudentsManagement: 'Gestion des Élèves',
    tabProgressionTracking: 'Suivi de Progression',
    tabCertificates: 'Certificats & Attestations',
    tabSchoolLogs: 'Journal de l\'Auto-École',
    totalStudentsKpi: 'Total Élèves',
    totalStudentsDesc: 'Élèves sous votre établissement',
    activeTrainingKpi: 'En Formation Active',
    activeTrainingDesc: 'Période valide non expirée',
    avgProgressKpi: 'Progression Moyenne',
    avgProgressDesc: 'Avancement moyen aux cours',
    expiredTrainingKpi: 'Formations Expirées',
    expiredTrainingDesc: 'Bloqués automatiquement',
    schoolSuccessByModuleTitle: 'Taux de Réussite par Module',
    schoolSuccessByModuleSub: 'Pourcentage de vos élèves ayant validé chaque module',
    schoolStatsBadge: 'Statistiques de l\'École',
    studentStatusPieTitle: 'Statut des Élèves',
    studentStatusPieSub: 'Répartition par état de formation',
    enrollmentEvolutionTitle: 'Évolution des Inscriptions Élèves',
    enrollmentEvolutionSub: 'Progression mensuelle des nouveaux inscrits dans votre établissement',
    studentEnrollmentLegend: 'Inscriptions élèves',
    recentRegisteredStudents: 'Derniers Élèves Inscrits',
    studentFullNameTh: 'Nom & Prénom',
    studentUniqueCodeTh: 'Code Unique Élève',
    endOfTrainingTh: 'Fin de Formation',
    studentProgressTh: 'Progression',
    accessStatusTh: 'Statut Accès',
    studentFallback: 'Élève',
    customizationTitle: 'Personnalisation de l\'Espace Élève',
    customizationDesc: 'Vos élèves verront vos couleurs, votre logo et votre slogan sur leur portail d\'apprentissage.',
    schoolLogoLabel: 'Logo de l\'Auto-École',
    directImportOrUrl: 'Importation directe ou URL',
    logoPreviewAlt: 'Aperçu Logo',
    logoUploadedBadge: 'Logo chargé',
    clickToChangeLogo: 'Cliquez pour changer d\'image depuis votre terminal',
    deleteLogoBtn: 'Supprimer le logo',
    importLogoTerminalTitle: 'Importer une image depuis votre terminal / appareil',
    dragAndDropLogoHelp: 'Glissez-déposez votre logo ici ou cliquez pour parcourir vos fichiers (PNG, JPG, SVG, WebP)',
    orDirectUrlAccordion: 'Ou coller une URL Web directe...',
    primaryColorFieldLabel: 'Couleur Primaire (Boutons & En-tête)',
    secondaryColorFieldLabel: 'Couleur Secondaire (Validation / Badges)',
    sloganFieldLabel: 'Slogan ou Message d\'Accueil Élève',
    sloganTextareaPlaceholder: 'Ex: Bienvenue sur l\'espace d\'entraînement théorique de notre auto-école !',
    saveAndApplyThemeBtn: 'Enregistrer et Appliquer la Charte',
    livePreviewTitle: 'Aperçu en Direct',
    yourSchoolFallback: 'Votre Auto-École',
    manageRegisteredStudentsTitle: 'Gestion de vos Élèves Inscrits',
    allPermisOption: 'Tous les Permis (Permis B)',
    permisBSelectOption: 'Permis B (Voiture)',
    advancedFiltersLabel: 'Filtres Avancés :',
    filterProgressionLabel: 'Progression :',
    allProgressOption: 'Toutes les progressions (0-100%)',
    notStarted0Pct: '0% (Non démarré)',
    beginner1to49Pct: '1% à 49% (Débutant)',
    advanced50to99Pct: '50% à 99% (Avancé)',
    completed100Pct: '100% (Terminé)',
    filterCertificatLabel: 'Certificat :',
    allCertificatesOption: 'Tous les certificats',
    inProgressCertOption: 'En cours (< 100%)',
    eligibleCertOption: 'Éligible (100% sans attestation)',
    generatedCertOption: 'Certificat Généré',
    downloadedCertOption: 'Certificat Téléchargé',
    sortByLabel: 'Trier par :',
    sortRecentInscriptions: 'Inscriptions récentes',
    sortProgressHighToLow: 'Progression : Forte → Faible (100% → 0%)',
    sortProgressLowToHigh: 'Progression : Faible → Forte (0% → 100%)',
    sortNameAtoZ: 'Nom (A - Z)',
    sortNameZtoA: 'Nom (Z - A)',
    resetFiltersBtn: 'Réinitialiser les filtres',
    permisColumnTh: 'Permis',
    trainingPeriodTh: 'Période Formation',
    certificateColumnTh: 'Attestation',
    noMatchingStudentsFound: 'Aucun élève ne correspond aux critères de recherche et filtres sélectionnés.',
    dateFromTo: 'Du {start} au {end}',
    certStatusDownloaded: 'Téléchargé',
    certStatusGenerated: 'Généré',
    certStatusEligible: 'Éligible (100%)',
    certStatusNotEligible: 'Non éligible',
    unlockStudentAccessTitle: 'Débloquer l\'accès élève',
    blockStudentAccessTitle: 'Suspendre/Bloquer l\'accès élève',
    unblockBtn: 'Débloquer',
    blockBtn: 'Bloquer',
    progressionTrackingTitle: 'Suivi de la Progression & Avancement des Cours',
    progressionTrackingSubtitle: 'Analyse détaillée de la réussite par module et du suivi individuel des élèves.',
    globalModuleAnalyticsTitle: 'Progression Globale des Modules Théoriques (Recharts Analytics)',
    globalModuleAnalyticsSubtitle: 'Taux moyen d\'avancement et de validation des questions par module de formation.',
    seeModuleDetailsLink: 'Voir détails des modules →',
    certificatesManagementTitle: 'Gestion des Certificats de Formation',
    certificatesManagementSubtitle: 'Générez, suivez l\'éligibilité et exportez les attestations officielles de réussite au Code de la Route au format PDF.',
    kpiCertGenerated: 'Générés',
    kpiCertGeneratedSub: 'Certificats officiels attribués',
    kpiCertDownloaded: 'Téléchargés (PDF)',
    kpiCertDownloadedSub: 'Exportés par les élèves / auto-école',
    kpiCertEligible: 'Éligibles à Émettre',
    kpiCertEligibleSub: '100% de progression validée',
    kpiCertInProgress: 'En Formation',
    kpiCertInProgressSub: 'Progression en cours (< 100%)',
    searchCertPlaceholder: 'Rechercher par élève, email, code...',
    allTabFilter: 'Tous',
    studentAndIdTh: 'Élève & Identifiant',
    certStatusTh: 'Statut Certificat',
    codeAndEmissionTh: 'Code & Émission',
    nameNotDefined: 'Nom non défini',
    statusCertDownloadedBadge: 'Téléchargé',
    statusCertGeneratedBadge: 'Généré (Prêt)',
    statusCertEligibleBadge: 'Éligible (À Générer)',
    statusCertInProgressBadge: 'En Cours (<100%)',
    notIssued: 'Non émis',
    generateCertBtn: 'Générer',
    previewDiplomaBtn: 'Aperçu',
    pdfBtn: 'PDF',
    schoolLogsTitle: 'Journal des Actions de l\'Auto-École',

    // Modals in AutoEcole
    registerNewStudentModalTitle: 'Inscrire un Nouvel Élève',
    studentFullNameRequired: 'Nom Complet Élève *',
    studentNamePlaceholder: 'Ex: Jean Dupont',
    studentEmailRequired: 'Email Élève *',
    studentPhoneLabel: 'Téléphone',
    initialStudentPasswordRequired: 'Mot de passe initial *',
    targetPermisCategoryRequired: 'Catégorie Permis Visée *',
    trainingProgramLabel: 'Programme de Formation',
    standardProgramDefault: '-- Programme Standard --',
    modulesCountSuffix: 'modules',
    startDateRequired: 'Date Début Formation *',
    endDateRequired: 'Date Fin (Blocage Auto) *',
    generateRegistrationBtn: 'Générer Inscription',
    csvBulkImportModalTitle: 'Importation Groupée d\'Élèves (CSV)',
    csvBulkImportSubtitle: 'Ajoutez rapidement plusieurs élèves à votre établissement',
    csvExpectedFormat: 'Format attendu : Nom, Email, Téléphone, Password, DateDébut, DateFin',
    downloadCsvTemplateBtn: 'Télécharger Modèle CSV',
    step1SelectCsvFile: '1. Sélectionner un fichier .CSV',
    step2OrPasteCsv: 'Ou 2. Coller directement le contenu CSV',
    csvTextareaPlaceholder: 'Nom,Email,Téléphone,MotDePasse,DateDebut,DateFin...',
    previewDetectedStudents: 'Aperçu des élèves détectés',
    validFormatBadge: 'Format Valide',
    csvImportCompletedSuccess: 'Importation terminée : {count} élèves créés avec succès.',
    csvImportResultTitle: 'Résultat de l\'importation',
    alertsAndWarnings: 'Alertes / Avertissements',
    importingInProgress: 'Importation en cours...',
    launchImportBtn: 'Lancer L\'Importation',
    editStudentModalTitle: 'Modifier l\'Élève —',
    associatedProgramLabel: 'Programme Associé',
    manuallyBlockCheckbox: 'Bloquer / Suspendre manuellement l\'accès aux cours',
    updateBtn: 'Mettre à jour',
    globalProgressLabel: 'Progression Globale :',
    videoWatchedDetails: 'Temps de vidéo vu :',
    secondsRequired: 's requis',
    officialCertPreviewTitle: 'Aperçu du Certificat Officiel',
    schoolCodeLabel: 'Code Établissement :',
    matoaSaaSCertified: 'MATOA SaaS Certifié',
    certificateOfCompletionTitle: 'ATTESTATION DE RÉUSSITE',
    theoreticalDriverTrainingSub: 'Formation Théorique au Code de la Route',
    certAwardedTo: 'Le présent certificat est décerné officiellement à :',
    studentUniqueCodeLabel: 'Code Unique Élève :',
    certLegalValidationParagraph: 'Pour avoir suivi et validé l\'intégralité des modules de formation théorique de sécurité routière avec un score de validation global de',
    certCodeLabel: 'Code :',
    emissionDateLabel: 'Date d\'émission :',
    digitalStampVerified: 'CACHET NUMÉRIQUE VALIDÉ',
    downloadPdfBtn: 'Télécharger le PDF',
    viewLessonsModalTitle: 'Consultation des Leçons —',
    lessonsSuperAdminManagedNotice: 'Contenu officiel géré centralement par le Super Administrateur.',
    noLessonsConfiguredForModule: 'Aucune leçon individuelle configurée pour ce module.',
    lessonNumberPrefix: 'Leçon #',
    minDurationPrefix: 'Durée min :',
    noDescriptionProvided: 'Aucune description fournie.',
    openLessonVideoBtn: 'Ouvrir la vidéo de la leçon',
    quizOfficialPreviewTitle: 'Aperçu du Quiz Officiel —',
    regulatoryChronoDuration: 'Durée Chrono Réglementaire',
    minutesUnit: 'minutes',
    secondsUnit: 'secondes',
    minimumRequiredScore: 'Seuil Minimum Requis',
    goodAnswersPctSuffix: '% de bonnes réponses',
    quizQuestionsListTitle: 'Questions du Quiz',
    noQuestionsAddedYet: 'Aucune question n\'a été ajoutée pour l\'instant.',
    questionNumberPrefix: 'Question #',
    correctionIncludedBadge: 'Correction Incluse',
    correctAnswerBadge: 'Bonne Réponse',
    pedagogicalExplanationTitle: 'Explication Pédagogique :',

    // Student Portal (ElevePortal)
    unsupportedVideoFormat: 'Format de vidéo non supporté',
    newCourseNotificationTitle: 'Nouveau cours théorique : {title}',
    newCourseNotificationBody: 'Le module Permis {type} est accessible ({count} leçons vidéo avec quiz).',
    planningExpiredNotifTitle: '⚠️ Planning de formation expiré',
    planningImminentNotifTitle: '⏰ Planning de formation : Fin imminente',
    planningActiveNotifTitle: '📅 Planning de formation actif',
    planningExpiredNotifBody: 'Votre période de formation s\'est achevée le {date}.',
    planningActiveNotifBody: 'Accès formation valide du {start} au {end}.',
    accountStatusBadge: 'Statut Compte',
    certAvailableNotifTitle: '🏆 Certificat Officiel de Réussite Disponible !',
    certAvailableNotifBody: 'Vous avez complété 100% de votre programme de Code de la Route. Téléchargez votre attestation PDF dès maintenant.',
    validationBadge: 'Validation',
    officialStudentPortalBadge: 'Portail Élève Officiel',
    welcomeStudentPrefix: 'Bienvenue,',
    studentCodeLabel: 'Code Élève :',
    notifCenterTitle: 'Centre de Notifications',
    unreadBadge: 'non lues',
    allNotifsTab: 'Toutes',
    courseNotifsTab: 'Cours Théoriques',
    planningNotifsTab: 'Planning',
    noNotificationsAvailable: 'Aucune notification disponible.',
    markAllAsReadBtn: 'Tout marquer comme lu',
    codeProgressCardTitle: 'Progression du Code',
    training100CompletedBadge: '🎉 Formation 100% Complétée !',
    modulesInProgressBadge: 'Modules théoriques en cours',
    trainingPeriodExpiredTitle: 'Période de Formation Expirée',
    accessToModulesSuspendedTitle: 'Accès aux Modules Suspendu',
    trainingPeriodExpiredDesc: 'Votre période de formation s\'est terminée le {date}. Conformément aux règles métier, votre accès aux vidéos et quiz est verrouillé.',
    accountSuspendedDesc: 'Votre auto-école a suspendu votre compte. Veuillez contacter votre administration.',
    contactSchoolToReactivate: 'Veuillez contacter {school} au {contact} pour réactiver votre formation.',
    tabCodePath: 'Parcours de Code',
    tabMyOfficialCert: 'Mon Certificat Officiel',
    tabMyHistory: 'Mon Historique',
    tabStudentPanel: 'Panneaux Routiers',
    newCoursesAndAlertsBanner: 'Nouveaux Cours & Alertes',
    seeAllAlertsBtn: 'Voir toutes les alertes →',
    lockedPathNotice: 'Parcours Verrouillé (1 à 1)',
    minVideoLabel: 'Min vidéo :',
    quizRequiredLabel: 'Quiz requis :',
    moduleCounterLabel: 'Module',
    moduleValidatedBadge: 'Module Validé',
    lessonsFinishedQuizUnlocked: 'Leçons Terminées → Quiz de Module Débloqué',
    inLearningProcess: 'En cours d\'apprentissage',
    moduleSummaryTitle: 'Résumé du Module',
    learningObjectivesTitle: 'Objectifs Pédagogiques',
    moduleLessonsCount: 'Leçons du Module',
    lessonsProgressCounter: 'Progrès : {completed} / {total} complétée(s)',
    lessonBadge: 'Leçon',
    minutesShort: 'min',
    miniQuizBadge: 'Mini-Quiz',
    activeLessonNumber: 'Leçon Active #',
    videoValidatedBadge: 'Vidéo Validée',
    videoLearningSessionTitle: 'Session vidéo d\'apprentissage',
    immersiveVideoTooltip: 'Passer la vidéo en mode immersif sans distraction',
    lessonWatchTimeLabel: 'Temps de visionnage de la leçon',
    watchTimeCounter: '{current}s / {required}s requis',
    miniQuizRevisionTitle: 'Mini-Quiz de Révision de la Leçon',
    miniQuizValidatedStatus: 'Mini-quiz validé ({score}%)',
    miniQuizPendingPrompt: 'Répondez aux questions rapides pour tester vos connaissances avant la suite.',
    watchVideoFirstBtn: 'Visionner la vidéo',
    retakeMiniQuizBtn: 'Refaire le Mini-Quiz',
    startMiniQuizBtn: 'Commencer le Mini-Quiz',
    finalModuleQuizHeading: 'Évaluation Finale du Module ({score}% Requis)',
    finalModuleQuizDesc: 'Une fois toutes les leçons terminées, passez le quiz final du module pour débloquer le module suivant.',
    completeAllLessonsFirstBtn: 'Compléter toutes les leçons d\'abord',
    startModuleQuizBtn: 'Commencer le Quiz de Module',
    selectModuleToStartMessage: 'Sélectionnez un module pour démarrer les cours.',
    trainingAccessField: 'Accès Formation',
    totalVideoWatchTimeSub: 'Temps de visionnage vidéo cumulé',
    testsPassedCountSub: '{count} épreuve(s) passée(s)',
    validatedModulesKpi: 'Modules Validés',
    unlockedTheoreticalModules: 'Modules théoriques débloqués',
    validated100Pct: 'Validé (100%)',
    moduleProgressLabel: 'Progression Module',
    lessonsDetailLine: 'Leçons : {completed} / {total} terminées',
    watchTimeDetailLine: 'Visionnage : {minutes} min {seconds} sec',
    finalQuizDetailLine: 'Quiz Final :',
    notTakenYet: 'Non passé',
    officialMatoaCertTitle: 'Certificat Officiel Matoa',
    officialCertDesc: 'Attestation de fin de formation théorique certifiée par l\'établissement',
    congrats100SuccessBanner: '🎉 Félicitations ! Vous avez validé 100% des modules théoriques. Votre attestation est prête.',
    viewAndPrintCertBtn: 'Consulter & Imprimer Mon Certificat',
    completeAllModulesToUnlockCert: '🔒 Complétez l\'ensemble des modules théoriques à 100% pour débloquer votre attestation.',
    currentProgressLabel: 'Progression actuelle :',
    activityHistoryTitle: 'Historique de vos Activités',
    studentsPanelTitle: 'Panneau des Élèves',
    miniQuizLessonModalBadge: 'Mini-Quiz de Leçon',
    miniQuizPassedTitle: 'Mini-Quiz Validé !',
    continueRevisingTitle: 'Continuez vos Révisions',
    goodAnswersSummary: '{correct} bonne(s) réponse(s) sur {total}',
    correctionAndExplanationsTitle: 'Correction et Explications',
    yourAnswerLabel: 'Votre réponse :',
    unansweredQuestion: 'Non répondue',
    correctAnswerLabel: 'Réponse correcte :',
    explanationLabel: 'Explication :',
    retryBtn: 'Réessayer',
    validateMiniQuizBtn: 'Valider le Mini-Quiz',
    quizEvaluationModalBadge: 'Évaluation Quiz —',
    minScoreRequiredBadge: 'Score minimum requis :',
    quizSucceededTitle: 'Quiz Réussi !',
    insufficientScoreTitle: 'Score Insuffisant',
    quizPassedSuccessDesc: '🎉 Bravo ! Le module est désormais validé. Le module suivant a été débloqué dans votre parcours.',
    quizFailedScoreDesc: 'Vous devez obtenir au moins {score}% pour valider ce module. Révisez le cours et réessayez.',
    retryQuizBtn: 'Réessayer le Quiz',
    closeAndContinueBtn: 'Fermer et Continuer',
    submitMyAnswersBtn: 'Valider et Soumettre Mes Réponses',

    // Component: BrandingPreviewCard
    studentSpacePreviewHeader: 'Aperçu Espace Élève —',
    customizedSpaceBadge: 'Espace Personnalisé',
    schoolLogoAlt: 'Logo Auto-École',
    officialStudentSpaceBadge: 'Espace Élève Officiel',
    schoolNameFallback: 'Nom de votre Auto-École',
    schoolSloganFallback: 'Plateforme de formation théorique en ligne.',
    theoreticalProgressSubtitle: 'Progression Théorique',
    mockModuleTitle: 'Module 1 : Signalisation routière',
    validated85PctBadge: 'Validé (85%)',
    primaryColorCardLabel: 'Couleur Primaire :',
    secondaryColorCardLabel: 'Couleur Secondaire :',

    // Component: CertificateModal
    saasNo1Badge: 'Plateforme SaaS N°1 Auto-Écoles',
    partnerSchoolFallback: 'Auto-École Partenaire',
    officialSuccessAttestationBadge: 'Attestation Officielle de Reussite',
    certEndTrainingTitle: 'CERTIFICAT DE FIN DE FORMATION THÉORIQUE',
    certLegalRequirementsDesc: 'Délivré conformément aux exigences réglementaires de suivi et de validation des modules de sécurité routière.',
    certAttestsThatStudent: 'Le présent certificat atteste que l\'élève',
    certRecipientFollowedModules: 'A suivi l\'intégralité des modules de formation théorique pour le',
    certTaughtBySchool: 'dispensés par',
    certPlatformSuccessConclusion: 'via la plateforme certifiée Matoa, et a validé l\'ensemble des évaluations et quiz requis avec succès.',
    verificationNumberLabel: 'N° de vérification :',
    certAssiduityNotice: 'Ce document atteste de votre assiduité et réussite théorique.',
    downloadAttestationPdfBtn: 'Télécharger l\'Attestation (PDF)',

    // Component: ModuleProgressionCharts
    pieValidated100: 'Validés (100%)',
    pieInProgress: 'En cours',
    pieToDoLocked: 'A faire / Verrouillés',
    theoreticalProgressAnalysisTitle: 'Analyse Visuelle de la Progression Théorique',
    theoreticalProgressAnalysisSub: 'Graphique circulaire global et jauges d\'avancement par module',
    globalAverageBadgeLabel: 'Moyenne Globale :',
    moduleStatusBreakdownTitle: 'Répartition par Statut des Modules',
    moduleUnitsTooltip: 'module(s)',
    gaugeProgressTitle: 'Progression par Module (Jauges Circulaires)',
    modAbbr: 'Mod',
    lessonsAndQuizCounter: 'Leçons : {completed}/{total} • Quiz : {score}',

    // Component: SplashScreen
    initMatoa: 'Initialisation de Matoa...',
    initMatoaSaaS: 'Initialisation de Matoa SaaS...',
    loadingModulesSecurity: 'Chargement des modules & sécurité...',
    checkingSchoolSpace: 'Vérification de l\'espace auto-école...',
    welcomeToMatoa: 'Bienvenue sur Matoa !',
    splashSubtitle: 'Plateforme SaaS Multi-Tenant & Formation Conduite',
    splashSecurityFooter: 'Accès sécurisé & SSL 256-bit — Matoa SaaS Engine',
  },

  en: {
    // General & Platform
    appName: 'Matoa',
    platformSubtitle: 'Driving School SaaS',
    platformSubtitleLong: 'Multi-Tenant SaaS Platform for Driving Schools',
    platformAdminBadge: 'SaaS Admin Platform',
    copyrightFooter: 'Matoa SaaS © 2026 — Secure Driving School Training Platform.',
    logout: 'Log Out',
    language: 'Language',
    themeLight: 'Light Mode',
    themeDark: 'Dark Mode',
    switchThemeToLight: 'Switch to light mode',
    switchThemeToDark: 'Switch to dark mode',
    loading: 'Loading...',
    save: 'Save',
    saving: 'Saving...',
    cancel: 'Cancel',
    close: 'Close',
    delete: 'Delete',
    edit: 'Edit',
    actions: 'Actions',
    status: 'Status',
    progress: 'Progress',
    codeUnique: 'Unique Code',
    name: 'Name',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Physical Address',
    startDate: 'Start Date',
    endDate: 'End Date',
    details: 'Details',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    errorOccurred: 'An error occurred.',
    search: 'Search',
    searchPlaceholder: 'Search student, email, code...',
    searchLogsPlaceholder: 'Search audit logs...',
    refresh: 'Refresh',
    fullscreen: 'Fullscreen',
    normalScreen: 'Normal',
    exitFullscreen: 'Exit Fullscreen',

    // Roles
    roleSuperAdmin: 'Super Admin',
    roleAutoEcole: 'Driving School Admin',
    roleEleve: 'Student',
    roleLabel: 'Matoa Platform Role:',

    // Statuses
    active: 'Active',
    operational: 'Operational',
    blocked: 'Blocked',
    suspended: 'Suspended',
    expired: 'Expired',
    completed: 'Certified',
    valid: 'Valid',
    accessValid: 'Valid Access',
    notStarted: 'Not started',
    inProgress: 'In progress',
    locked: 'Locked',
    available: 'Available',
    validated: 'Validated',

    // Exports
    exportPdf: 'Export to PDF',
    exportExcel: 'Export to Excel (CSV)',
    exportStats: 'Export Statistics',
    exportStudentsList: 'Export Students List',
    exportCsv: 'Export CSV',
    exportJson: 'Export JSON',
    exportCsvStudents: 'CSV Students',
    exportCsvCourses: 'CSV Courses',
    exportPdfReport: 'PDF Report',
    globalNetworkReport: 'Matoa Global Network Report',

    // Login Page
    loginStudentTab: 'Student',
    loginSchoolTab: 'Driving School',
    loginAdminTab: 'Super Admin',
    loginAutoEcoleCode: 'Unique School Code *',
    loginAutoEcoleCodePlaceholder: 'MATOA-AE-...',
    loginAutoEcoleCodeHint: 'Provided by your driving school during registration.',
    loginStudentCodeOrEmail: 'Student Code (or Email) *',
    loginStudentCodePlaceholder: 'Enter your student code or email',
    loginEmailProfessional: 'Professional Email Address *',
    loginPassword: 'Password *',
    loginConnecting: 'Logging in...',
    loginSubmit: 'Sign In to Workspace',
    loginSuspendedTitle: '⛔ ACCOUNT ACCESS SUSPENDED',

    // Header Navbar & Settings
    accountSettings: 'Account Settings',
    accountSettingsSubtitle: 'Manage personal details and platform preferences',
    tabPersonalProfile: 'Personal Profile',
    tabSecurityPassword: 'Security & Password',
    tabNotifications: 'Notifications',
    currentPassword: 'Current password',
    newPassword: 'New password',
    newPasswordPlaceholder: 'Minimum 6 characters',
    confirmNewPassword: 'Confirm new password',
    confirmPasswordPlaceholder: 'Repeat new password',
    notifUnlockModules: 'New Modules Unlocked',
    notifUnlockModulesDesc: 'Receive email when a module is unlocked',
    notifQuizResults: 'Quiz Results & Certificates',
    notifQuizResultsDesc: 'Email confirmation when quizzes are completed',
    notifExpiryReminder: 'Training Expiration Reminder',
    notifExpiryReminderDesc: 'Alerts 15 days before access validity ends',
    notifSms: 'SMS Notifications',
    notifSmsDesc: 'Direct alert on mobile (optional)',
    settingsUpdatedSuccess: 'Your settings have been updated successfully.',
    passwordRequiredError: 'Please enter a new password.',
    passwordMismatchError: 'The new passwords do not match.',

    // Super Admin Dashboard
    superAdminDashboardTitle: 'Matoa Super Admin Dashboard',
    superAdminDashboardSubtitle: 'Global oversight of driving schools, theoretical modules management, and audit logs.',
    createSchoolBtn: 'Register Driving School',
    createModuleBtn: 'Create Module',
    tabOverview: 'Overview',
    tabSchoolsFleet: 'Driving Schools Fleet',
    tabLicencePrograms: 'Licence Programs',
    tabModulesAndQuizzes: 'Modules & Quizzes',
    tabActivityLogs: 'Global Activity Logs',
    totalSchools: 'Total Driving Schools',
    activeSchoolsCount: 'active school(s)',
    totalStudentsRegistered: 'Total Registered Students',
    acrossAllSchools: 'Across all partner schools',
    averageProgress: 'Average Progress',
    studentsCodeProgress: 'Students progress in Code theory',
    certificatesEarned: 'Certificates Earned',
    fullCompletedTrainings: '100% completed courses',
    enrollmentAndCertTrends: 'Enrollment & Certification Trends',
    monthlyNetworkEvolution: 'Monthly global network trends',
    inscriptionsLegend: 'Enrollments',
    certificationsLegend: 'Certifications',
    progressBreakdown: 'Progress Breakdown',
    progressDistributionRanges: 'Distribution across progress ranges',
    moduleSuccessRate: 'Theoretical Modules Success Rate',
    moduleSuccessRateSub: 'Percentage of students passing each module',
    successRate: 'Success rate',
    recentPartnerSchools: 'Recent Partner Driving Schools',
    schoolNameTh: 'School Name',
    schoolCodeTh: 'Unique School Code',
    contactTh: 'Contact',
    studentsEnrolledTh: 'Enrolled Students',
    suspendBtn: 'Suspend',
    activateBtn: 'Activate',
    manageSchoolsFleetTitle: 'Driving Schools Fleet Management',
    newSchoolBtn: 'New Driving School',
    noSloganFallback: 'No specific slogan.',
    adminContactEmail: 'Admin Contact Email:',
    phoneLabel: 'Phone:',
    notProvided: 'Not provided',
    studentsCountLabel: 'Registered students:',
    themeLabel: 'Theme:',
    primaryColor: 'Primary',
    secondaryColor: 'Secondary',
    deleteSchoolConfirmTitle: 'Delete Driving School?',
    deleteSchoolConfirmWarning: 'Warning: This action is irreversible. Deleting this school will permanently delete all associated student accounts and activity history.',
    confirmDelete: 'Confirm Deletion',
    licenceProgramsTitle: 'Training Programs by Licence Category',
    licenceProgramsSubtitle: 'Create and customize dedicated curricula for each licence category (A, B, C, D, etc.).',
    newProgramBtn: 'New Licence Program',
    noProgramDefined: 'No licence program defined',
    noProgramDefinedHelp: 'Click "New Licence Program" to attach modules to each category.',
    modulesIncludedInProgram: 'Modules included in this program:',
    allActiveModules: 'All active modules',
    theoreticalModulesTitle: 'Theoretical Training Modules',
    theoreticalModulesSubtitle: 'Each module includes a summary, N lessons (with 5-question mini-quizzes) and a 10-question final module quiz.',
    resetPermisBBtn: 'Reset Category B (10 Modules)',
    newModuleBtn: 'New Module',
    orderPrefix: 'Order',
    lessonsChip: 'Lesson(s)',
    quizEndChip: 'Final Quiz:',
    minScoreChip: 'Min Score:',
    manageLessonsAndMiniQuiz: 'Manage Lessons & Mini-Quiz (5Q)',
    finalModuleQuizAction: 'Final Module Quiz',
    globalLogsTitle: 'Platform Activity Audit Logs',
    userFallback: 'User',

    // Modals in SuperAdmin
    createSchoolModalTitle: 'Register New Driving School',
    schoolNameRequired: 'School Name *',
    schoolNamePlaceholder: 'Ex: Premier Driving Academy',
    physicalAddress: 'Physical Address',
    physicalAddressPlaceholder: 'Ex: 15 Oxford Street, London',
    adminEmailRequired: 'Admin Email *',
    initialPasswordRequired: 'Initial Password *',
    primaryColorLabel: 'Primary Color',
    secondaryColorLabel: 'Secondary Color',
    sloganLabel: 'Slogan',
    sloganPlaceholder: 'Welcome slogan...',
    createAndGenerateCode: 'Create & Generate School Code',
    editSchoolModalTitle: 'Edit Driving School —',
    contactEmail: 'Contact Email',
    logoUrlLabel: 'Logo URL',
    updateSchoolBtn: 'Update Driving School',
    createModuleModalTitle: 'New Theoretical Training Module',
    editModuleModalTitle: 'Edit Training Module',
    moduleTitleRequired: 'Module Title *',
    moduleTitlePlaceholder: 'Ex: Module 4: Lights and Road Illumination',
    moduleDescLabel: 'Description',
    moduleDescPlaceholder: 'Summary of the curriculum...',
    videoUrlRequired: 'MP4 Video URL *',
    durationSeconds: 'Duration (sec)',
    minWatchSeconds: 'Min Watch Time (sec)',
    minQuizPct: 'Min Quiz Score (%)',
    saveModuleBtn: 'Save Module',
    moduleQuizModalBadge: 'Module Final Quiz (10 Questions)',
    moduleQuizModalTitle: 'Quiz Editor —',
    quizChronoSeconds: 'Final Quiz Timer (seconds)',
    totalQuestionsCount: 'Total Questions:',
    generate10QuestionsBtn: 'Generate 10 Questions',
    questionIndex: 'Question',
    questionTextPlaceholder: 'Question prompt...',
    answerOptionsPrompt: 'Answer options (Check the correct answer):',
    pedagogicalExplanation: 'Pedagogical explanation:',
    explanationPlaceholder: 'Explanation displayed after answering...',
    addQuestionToQuiz: '+ Add Question to Quiz',
    saveFinalQuizBtn: 'Save Final Quiz (10Q)',
    lessonsModalBadge: 'Module Structure: N Lessons & Mini-Quizzes (5Q)',
    lessonsModalTitle: 'Lessons Management —',
    lessonIndex: 'Lesson',
    deleteLessonBtn: 'Delete Lesson',
    lessonTitleLabel: 'Lesson Title',
    lessonTitlePlaceholder: 'Lesson title...',
    lessonSummaryLabel: 'Lesson Summary / Description',
    lessonSummaryPlaceholder: 'Short summary of this lesson...',
    lessonVideoUrlLabel: 'Video URL',
    activateMiniQuizCheckbox: 'Enable 5-question mini-quiz after this lesson',
    generate5MiniQuizBtn: 'Generate 5 Mini-Quiz Questions',
    miniQuizQuestionsHeader: 'Mini-Quiz Questions (5 recommended):',
    deleteQuestionBtn: 'Delete Q',
    addQuestionToMiniQuiz: '+ Add question to mini-quiz',
    addLessonToModule: '+ Add Lesson to Module',
    saveLessonsAndMiniQuizBtn: 'Save Lessons & Mini-Quizzes',
    newProgramModalTitle: 'New Licence Program',
    editProgramModalTitle: 'Edit Licence Program',
    programSubtitle: 'Define the licence category and applicable training modules.',
    categoryPermisLabel: 'Licence Category / Type *',
    permisBOption: 'Category B (Car / Passenger Vehicle)',
    programTitleRequired: 'Program Title *',
    programTitlePlaceholder: 'e.g. Category B Driving Program',
    programDescAndGoals: 'Description & Objectives',
    programDescPlaceholder: 'Learning objectives and training rules...',
    selectModulesToInclude: 'Select Modules to Include in this Program:',
    saveProgramBtn: 'Save Program',

    // Auto-Ecole Dashboard
    schoolCodeBadge: 'Unique Code:',
    schoolDefaultSlogan: 'Theoretical Highway Code Learning Platform',
    quickSearchPlaceholder: 'Quick student search (Name, Code MATOA-EL-..., Email, Phone)...',
    clearSearchTitle: 'Clear search',
    foundRecords: 'Records found',
    closeDropdown: 'Close ✕',
    noStudentFoundFor: 'No student record found for',
    permisPrefix: 'Category',
    trackingBtn: 'Tracking',
    editBtn: 'Edit',
    tabBranding: 'Branding & Theme',
    tabStudentsManagement: 'Students Management',
    tabProgressionTracking: 'Progression Tracking',
    tabCertificates: 'Certificates & Diplomas',
    tabSchoolLogs: 'School Activity Log',
    totalStudentsKpi: 'Total Students',
    totalStudentsDesc: 'Students under your school',
    activeTrainingKpi: 'In Active Training',
    activeTrainingDesc: 'Valid non-expired period',
    avgProgressKpi: 'Average Progress',
    avgProgressDesc: 'Average course progression',
    expiredTrainingKpi: 'Expired Trainings',
    expiredTrainingDesc: 'Automatically locked',
    schoolSuccessByModuleTitle: 'Success Rate by Module',
    schoolSuccessByModuleSub: 'Percentage of students who passed each module',
    schoolStatsBadge: 'School Analytics',
    studentStatusPieTitle: 'Student Status Breakdown',
    studentStatusPieSub: 'Distribution by training status',
    enrollmentEvolutionTitle: 'Student Enrollment Evolution',
    enrollmentEvolutionSub: 'Monthly new student registrations in your school',
    studentEnrollmentLegend: 'Student enrollments',
    recentRegisteredStudents: 'Recently Enrolled Students',
    studentFullNameTh: 'Full Name',
    studentUniqueCodeTh: 'Student Code',
    endOfTrainingTh: 'End of Training',
    studentProgressTh: 'Progress',
    accessStatusTh: 'Access Status',
    studentFallback: 'Student',
    customizationTitle: 'Student Portal Customization',
    customizationDesc: 'Your students will see your colors, logo, and slogan on their learning portal.',
    schoolLogoLabel: 'Driving School Logo',
    directImportOrUrl: 'Direct upload or URL',
    logoPreviewAlt: 'Logo Preview',
    logoUploadedBadge: 'Logo loaded',
    clickToChangeLogo: 'Click to change image from your device',
    deleteLogoBtn: 'Delete logo',
    importLogoTerminalTitle: 'Import image from your device',
    dragAndDropLogoHelp: 'Drag & drop your logo here or click to browse files (PNG, JPG, SVG, WebP)',
    orDirectUrlAccordion: 'Or paste direct web URL...',
    primaryColorFieldLabel: 'Primary Color (Buttons & Header)',
    secondaryColorFieldLabel: 'Secondary Color (Validation & Badges)',
    sloganFieldLabel: 'Student Welcome Slogan or Greeting',
    sloganTextareaPlaceholder: 'Ex: Welcome to our online theoretical training workspace!',
    saveAndApplyThemeBtn: 'Save and Apply Brand Identity',
    livePreviewTitle: 'Live Preview',
    yourSchoolFallback: 'Your Driving School',
    manageRegisteredStudentsTitle: 'Registered Students Management',
    allPermisOption: 'All Categories (Category B)',
    permisBSelectOption: 'Category B (Car)',
    advancedFiltersLabel: 'Advanced Filters:',
    filterProgressionLabel: 'Progress:',
    allProgressOption: 'All Progress (0-100%)',
    notStarted0Pct: '0% (Not Started)',
    beginner1to49Pct: '1% to 49% (Beginner)',
    advanced50to99Pct: '50% to 99% (Advanced)',
    completed100Pct: '100% (Completed)',
    filterCertificatLabel: 'Certificate:',
    allCertificatesOption: 'All Certificates',
    inProgressCertOption: 'In Progress (< 100%)',
    eligibleCertOption: 'Eligible (100% unissued)',
    generatedCertOption: 'Certificate Generated',
    downloadedCertOption: 'Certificate Downloaded',
    sortByLabel: 'Sort by:',
    sortRecentInscriptions: 'Recent registrations',
    sortProgressHighToLow: 'Progress: High → Low (100% → 0%)',
    sortProgressLowToHigh: 'Progress: Low → High (0% → 100%)',
    sortNameAtoZ: 'Name (A - Z)',
    sortNameZtoA: 'Name (Z - A)',
    resetFiltersBtn: 'Reset filters',
    permisColumnTh: 'Category',
    trainingPeriodTh: 'Training Period',
    certificateColumnTh: 'Certificate',
    noMatchingStudentsFound: 'No student matches the search criteria and selected filters.',
    dateFromTo: 'From {start} to {end}',
    certStatusDownloaded: 'Downloaded',
    certStatusGenerated: 'Generated',
    certStatusEligible: 'Eligible (100%)',
    certStatusNotEligible: 'Not eligible',
    unlockStudentAccessTitle: 'Unlock student access',
    blockStudentAccessTitle: 'Suspend / Block student access',
    unblockBtn: 'Unblock',
    blockBtn: 'Block',
    progressionTrackingTitle: 'Course Progression & Tracking',
    progressionTrackingSubtitle: 'Detailed analysis of module completion and individual student progress.',
    globalModuleAnalyticsTitle: 'Global Module Analytics (Recharts)',
    globalModuleAnalyticsSubtitle: 'Average progression and question pass rate by theoretical module.',
    seeModuleDetailsLink: 'View module breakdown →',
    certificatesManagementTitle: 'Training Certificates Management',
    certificatesManagementSubtitle: 'Generate, track eligibility, and export official Highway Code completion certificates to PDF.',
    kpiCertGenerated: 'Generated',
    kpiCertGeneratedSub: 'Official certificates issued',
    kpiCertDownloaded: 'Downloaded (PDF)',
    kpiCertDownloadedSub: 'Exported by students / school',
    kpiCertEligible: 'Eligible to Issue',
    kpiCertEligibleSub: '100% verified progression',
    kpiCertInProgress: 'In Training',
    kpiCertInProgressSub: 'Ongoing progression (< 100%)',
    searchCertPlaceholder: 'Search by student, email, code...',
    allTabFilter: 'All',
    studentAndIdTh: 'Student & ID',
    certStatusTh: 'Certificate Status',
    codeAndEmissionTh: 'Code & Issue Date',
    nameNotDefined: 'Name not set',
    statusCertDownloadedBadge: 'Downloaded',
    statusCertGeneratedBadge: 'Generated (Ready)',
    statusCertEligibleBadge: 'Eligible (To Generate)',
    statusCertInProgressBadge: 'In Progress (<100%)',
    notIssued: 'Not issued',
    generateCertBtn: 'Generate',
    previewDiplomaBtn: 'Preview',
    pdfBtn: 'PDF',
    schoolLogsTitle: 'Driving School Activity Logs',

    // Modals in AutoEcole
    registerNewStudentModalTitle: 'Register New Student',
    studentFullNameRequired: 'Student Full Name *',
    studentNamePlaceholder: 'Ex: John Doe',
    studentEmailRequired: 'Student Email *',
    studentPhoneLabel: 'Phone Number',
    initialStudentPasswordRequired: 'Initial Password *',
    targetPermisCategoryRequired: 'Target Licence Category *',
    trainingProgramLabel: 'Training Program',
    standardProgramDefault: '-- Standard Program --',
    modulesCountSuffix: 'modules',
    startDateRequired: 'Training Start Date *',
    endDateRequired: 'End Date (Auto-Lock) *',
    generateRegistrationBtn: 'Create Registration',
    csvBulkImportModalTitle: 'CSV Bulk Student Import',
    csvBulkImportSubtitle: 'Quickly add multiple students to your driving school',
    csvExpectedFormat: 'Expected format: Name, Email, Phone, Password, StartDate, EndDate',
    downloadCsvTemplateBtn: 'Download CSV Template',
    step1SelectCsvFile: '1. Select a .CSV file',
    step2OrPasteCsv: 'Or 2. Paste CSV content directly',
    csvTextareaPlaceholder: 'Name,Email,Phone,Password,StartDate,EndDate...',
    previewDetectedStudents: 'Preview detected students',
    validFormatBadge: 'Valid Format',
    csvImportCompletedSuccess: 'Import completed: {count} students created successfully.',
    csvImportResultTitle: 'Import Results',
    alertsAndWarnings: 'Alerts / Warnings',
    importingInProgress: 'Importing in progress...',
    launchImportBtn: 'Start Import',
    editStudentModalTitle: 'Edit Student —',
    associatedProgramLabel: 'Associated Program',
    manuallyBlockCheckbox: 'Manually suspend / lock student course access',
    updateBtn: 'Update',
    globalProgressLabel: 'Overall Progress:',
    videoWatchedDetails: 'Video watch time:',
    secondsRequired: 's required',
    officialCertPreviewTitle: 'Official Certificate Preview',
    schoolCodeLabel: 'School Code:',
    matoaSaaSCertified: 'MATOA Certified SaaS',
    certificateOfCompletionTitle: 'CERTIFICATE OF ACHIEVEMENT',
    theoreticalDriverTrainingSub: 'Theoretical Road Code Training',
    certAwardedTo: 'This official certificate is awarded to:',
    studentUniqueCodeLabel: 'Unique Student Code:',
    certLegalValidationParagraph: 'For successfully completing and validating all theoretical road safety modules with an overall validation score of',
    certCodeLabel: 'Code:',
    emissionDateLabel: 'Issue Date:',
    digitalStampVerified: 'DIGITAL STAMP VERIFIED',
    downloadPdfBtn: 'Download PDF',
    viewLessonsModalTitle: 'Lessons Overview —',
    lessonsSuperAdminManagedNotice: 'Official curriculum centrally managed by Super Administrator.',
    noLessonsConfiguredForModule: 'No individual lessons configured for this module.',
    lessonNumberPrefix: 'Lesson #',
    minDurationPrefix: 'Min duration:',
    noDescriptionProvided: 'No description provided.',
    openLessonVideoBtn: 'Open lesson video',
    quizOfficialPreviewTitle: 'Official Quiz Preview —',
    regulatoryChronoDuration: 'Regulatory Countdown Timer',
    minutesUnit: 'minutes',
    secondsUnit: 'seconds',
    minimumRequiredScore: 'Minimum Required Score',
    goodAnswersPctSuffix: '% correct answers',
    quizQuestionsListTitle: 'Quiz Questions',
    noQuestionsAddedYet: 'No questions added yet.',
    questionNumberPrefix: 'Question #',
    correctionIncludedBadge: 'Correction Included',
    correctAnswerBadge: 'Correct Answer',
    pedagogicalExplanationTitle: 'Pedagogical Explanation:',

    // Student Portal (ElevePortal)
    unsupportedVideoFormat: 'Unsupported video format',
    newCourseNotificationTitle: 'New theoretical course: {title}',
    newCourseNotificationBody: 'Category {type} module is accessible ({count} video lessons with quiz).',
    planningExpiredNotifTitle: '⚠️ Training schedule expired',
    planningImminentNotifTitle: '⏰ Training schedule: Imminent expiration',
    planningActiveNotifTitle: '📅 Training schedule active',
    planningExpiredNotifBody: 'Your training period ended on {date}.',
    planningActiveNotifBody: 'Training access valid from {start} to {end}.',
    accountStatusBadge: 'Account Status',
    certAvailableNotifTitle: '🏆 Official Certificate of Achievement Available!',
    certAvailableNotifBody: 'You have completed 100% of your Highway Code curriculum. Download your official PDF certificate now.',
    validationBadge: 'Validation',
    officialStudentPortalBadge: 'Official Student Portal',
    welcomeStudentPrefix: 'Welcome,',
    studentCodeLabel: 'Student Code:',
    notifCenterTitle: 'Notification Center',
    unreadBadge: 'unread',
    allNotifsTab: 'All',
    courseNotifsTab: 'Theoretical Courses',
    planningNotifsTab: 'Schedule',
    noNotificationsAvailable: 'No notifications available.',
    markAllAsReadBtn: 'Mark all as read',
    codeProgressCardTitle: 'Highway Code Progress',
    training100CompletedBadge: '🎉 Training 100% Completed!',
    modulesInProgressBadge: 'Theoretical modules in progress',
    trainingPeriodExpiredTitle: 'Training Period Expired',
    accessToModulesSuspendedTitle: 'Module Access Suspended',
    trainingPeriodExpiredDesc: 'Your training period ended on {date}. In accordance with business rules, video and quiz access is locked.',
    accountSuspendedDesc: 'Your driving school has suspended your account. Please contact your administration.',
    contactSchoolToReactivate: 'Please contact {school} at {contact} to reactivate your training.',
    tabCodePath: 'Code Learning Path',
    tabMyOfficialCert: 'My Official Certificate',
    tabMyHistory: 'My History',
    tabStudentPanel: 'Road Signs',
    newCoursesAndAlertsBanner: 'New Courses & Alerts',
    seeAllAlertsBtn: 'View all alerts →',
    lockedPathNotice: 'Step-by-Step Locked Progression (1 by 1)',
    minVideoLabel: 'Min video:',
    quizRequiredLabel: 'Required quiz:',
    moduleCounterLabel: 'Module',
    moduleValidatedBadge: 'Module Validated',
    lessonsFinishedQuizUnlocked: 'Lessons Completed → Module Quiz Unlocked',
    inLearningProcess: 'Learning in progress',
    moduleSummaryTitle: 'Module Summary',
    learningObjectivesTitle: 'Learning Objectives',
    moduleLessonsCount: 'Module Lessons',
    lessonsProgressCounter: 'Progress: {completed} / {total} completed',
    lessonBadge: 'Lesson',
    minutesShort: 'min',
    miniQuizBadge: 'Mini-Quiz',
    activeLessonNumber: 'Active Lesson #',
    videoValidatedBadge: 'Video Validated',
    videoLearningSessionTitle: 'Video learning session',
    immersiveVideoTooltip: 'Switch video to distraction-free immersive mode',
    lessonWatchTimeLabel: 'Lesson watch time',
    watchTimeCounter: '{current}s / {required}s required',
    miniQuizRevisionTitle: 'Lesson Review Mini-Quiz',
    miniQuizValidatedStatus: 'Mini-quiz passed ({score}%)',
    miniQuizPendingPrompt: 'Answer the quick questions to test your knowledge before moving forward.',
    watchVideoFirstBtn: 'Watch video',
    retakeMiniQuizBtn: 'Retake Mini-Quiz',
    startMiniQuizBtn: 'Start Mini-Quiz',
    finalModuleQuizHeading: 'Module Final Evaluation ({score}% Required)',
    finalModuleQuizDesc: 'Once all lessons are finished, take the final module quiz to unlock the next module.',
    completeAllLessonsFirstBtn: 'Complete all lessons first',
    startModuleQuizBtn: 'Start Module Quiz',
    selectModuleToStartMessage: 'Select a module to start learning.',
    trainingAccessField: 'Training Access',
    totalVideoWatchTimeSub: 'Cumulative video study time',
    testsPassedCountSub: '{count} test(s) taken',
    validatedModulesKpi: 'Validated Modules',
    unlockedTheoreticalModules: 'Unlocked theoretical modules',
    validated100Pct: 'Validated (100%)',
    moduleProgressLabel: 'Module Progress',
    lessonsDetailLine: 'Lessons: {completed} / {total} finished',
    watchTimeDetailLine: 'Watch time: {minutes} min {seconds} sec',
    finalQuizDetailLine: 'Final Quiz:',
    notTakenYet: 'Not taken',
    officialMatoaCertTitle: 'Official Matoa Certificate',
    officialCertDesc: 'Theoretical course completion certificate certified by',
    congrats100SuccessBanner: '🎉 Congratulations! You have completed 100% of theoretical modules. Your certificate is ready.',
    viewAndPrintCertBtn: 'View & Print My Certificate',
    completeAllModulesToUnlockCert: '🔒 Complete 100% of all theoretical modules to unlock your certificate.',
    currentProgressLabel: 'Current progress:',
    activityHistoryTitle: 'Your Activity History',
    studentsPanelTitle: 'Road Signs & Guidelines',
    miniQuizLessonModalBadge: 'Lesson Mini-Quiz',
    miniQuizPassedTitle: 'Mini-Quiz Passed!',
    continueRevisingTitle: 'Keep Revising',
    goodAnswersSummary: '{correct} correct answer(s) out of {total}',
    correctionAndExplanationsTitle: 'Corrections & Explanations',
    yourAnswerLabel: 'Your answer:',
    unansweredQuestion: 'Unanswered',
    correctAnswerLabel: 'Correct answer:',
    explanationLabel: 'Explanation:',
    retryBtn: 'Retry',
    validateMiniQuizBtn: 'Submit Mini-Quiz',
    quizEvaluationModalBadge: 'Quiz Evaluation —',
    minScoreRequiredBadge: 'Minimum required score:',
    quizSucceededTitle: 'Quiz Passed!',
    insufficientScoreTitle: 'Insufficient Score',
    quizPassedSuccessDesc: '🎉 Bravo! The module is now validated. The next module is unlocked in your curriculum.',
    quizFailedScoreDesc: 'You need at least {score}% to pass this module. Review the lessons and try again.',
    retryQuizBtn: 'Retry Quiz',
    closeAndContinueBtn: 'Close & Continue',
    submitMyAnswersBtn: 'Submit My Answers',

    // Component: BrandingPreviewCard
    studentSpacePreviewHeader: 'Student Portal Preview —',
    customizedSpaceBadge: 'Custom Space',
    schoolLogoAlt: 'Driving School Logo',
    officialStudentSpaceBadge: 'Official Student Space',
    schoolNameFallback: 'Your Driving School Name',
    schoolSloganFallback: 'Online theoretical driver training platform.',
    theoreticalProgressSubtitle: 'Theoretical Progress',
    mockModuleTitle: 'Module 1: Road Signs and Markings',
    validated85PctBadge: 'Passed (85%)',
    primaryColorCardLabel: 'Primary Color:',
    secondaryColorCardLabel: 'Secondary Color:',

    // Component: CertificateModal
    saasNo1Badge: '#1 SaaS Platform for Driving Schools',
    partnerSchoolFallback: 'Partner Driving School',
    officialSuccessAttestationBadge: 'Official Certificate of Achievement',
    certEndTrainingTitle: 'THEORETICAL TRAINING COMPLETION CERTIFICATE',
    certLegalRequirementsDesc: 'Issued in accordance with regulatory tracking and validation standards for road safety modules.',
    certAttestsThatStudent: 'This certificate hereby confirms that student',
    certRecipientFollowedModules: 'Has completed all theoretical training modules for',
    certTaughtBySchool: 'conducted by',
    certPlatformSuccessConclusion: 'via the Matoa certified platform, and successfully passed all required quizzes and evaluations.',
    verificationNumberLabel: 'Verification No.:',
    certAssiduityNotice: 'This document certifies your study diligence and theoretical completion.',
    downloadAttestationPdfBtn: 'Download Certificate (PDF)',

    // Component: ModuleProgressionCharts
    pieValidated100: 'Validated (100%)',
    pieInProgress: 'In progress',
    pieToDoLocked: 'To do / Locked',
    theoreticalProgressAnalysisTitle: 'Visual Analysis of Theoretical Progress',
    theoreticalProgressAnalysisSub: 'Global donut chart and circular gauges per module',
    globalAverageBadgeLabel: 'Overall Average:',
    moduleStatusBreakdownTitle: 'Module Status Distribution',
    moduleUnitsTooltip: 'module(s)',
    gaugeProgressTitle: 'Module Progress (Circular Gauges)',
    modAbbr: 'Mod',
    lessonsAndQuizCounter: 'Lessons: {completed}/{total} • Quiz: {score}',

    // Component: SplashScreen
    initMatoa: 'Initializing Matoa...',
    initMatoaSaaS: 'Initializing Matoa SaaS...',
    loadingModulesSecurity: 'Loading modules & security...',
    checkingSchoolSpace: 'Verifying driving school workspace...',
    welcomeToMatoa: 'Welcome to Matoa!',
    splashSubtitle: 'Multi-Tenant SaaS Platform & Driver Education',
    splashSecurityFooter: 'Secure Access & 256-bit SSL — Matoa SaaS Engine',
  },
};

export type TranslationKey = keyof typeof translations.fr;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('matoa_lang');
    return (saved === 'en' || saved === 'fr') ? saved : 'fr';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('matoa_lang', lang);
  };

  const t = (key: TranslationKey, params?: Record<string, string | number>): string => {
    let text = (translations[language] as any)?.[key] || (translations['fr'] as any)?.[key] || (key as string);
    if (params) {
      Object.keys(params).forEach((paramKey) => {
        text = text.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(params[paramKey]));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
